import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppTheme = "light" | "dark";
export type AppLocale = "en" | "fr" | "ar";

const messages: Record<AppLocale, Record<string, string>> = {
  en: {
    dashboard: "Dashboard", inbox: "Sales Inbox", workforce: "Workforce", workItems: "WorkItems",
    approvals: "Approvals", analytics: "Analytics", workspace: "Workspace", department: "Department",
    salesDepartment: "Sales department", operatingSystem: "AI Workforce Operating System",
    lightTheme: "Light theme", darkTheme: "Dark theme", switchTheme: "Switch color theme",
    language: "Interface language", logout: "Log out", operator: "Operator",
    overview: "Overview", commandCenter: "AI workforce command center",
    commandDescription: "Monitor work requiring attention, current operations, workforce activity and AI usage.",
    aiEmployees: "AI employees", runningWork: "Running WorkItems", approvalRequired: "Approval required",
    failedWork: "Failed WorkItems", recentState: "Recent operational state", readiness: "Workspace readiness",
    conversations: "Conversations", inboxDescription: "Operate workspace Sales conversations and governed replies.",
    workforceDescription: "Inspect employees, capabilities, autonomy and approved tool access.",
    operations: "Operations", workItemsDescription: "Track work state, assignment, business results and failures.",
    humanReview: "Human review", approvalsDescription: "Review proposed business actions at the human decision boundary.",
    analyticsDescription: "Operational facts from WorkItems, approvals, AI accounting and Sales.",
    status: "Status", workType: "Work type", aiEmployee: "AI employee", capability: "Capability",
    filters: "Filters", all: "All", title: "Title", updated: "Updated", created: "Created",
    approve: "Approve", reject: "Reject", reviewDetails: "Review details", reviewerNote: "Reviewer note",
    proposedAction: "Proposed action", period: "Reporting period", humanControl: "Human control",
    aiUsage: "AI usage", cost: "Cost", completed: "Completed", failed: "Failed", active: "Active",
    inactive: "Inactive", enabled: "Enabled", disabled: "Disabled", pending: "pending",
    createdStatus: "Created", assigned: "Assigned", running: "Running", waiting: "Waiting",
    approval_required: "Approval required", completedStatus: "Completed", failedStatus: "Failed",
    cancelled: "Cancelled", expired: "Expired", noWorkspace: "No workspace",
    noWorkspaceAvailable: "No workspace available",
    noWorkspaceDescription: "Create or join a workspace before using the operating dashboard.",
    configuredWorkforce: "Configured workforce", currentState: "Current state", currentWorkItemState: "Current WorkItem state",
    safeAggregates: "Safe aggregates from FastAPI, not generated facts.", deliveredActions: "Delivered actions", failedActions: "Failed actions",
    estimatedAiSpend: "Estimated AI spend", workspaceSelected: "Workspace selected", integrationAccountActive: "Integration account active",
    approvalAnalyticsAvailable: "Approval analytics available", aiUsageAnalyticsAvailable: "AI usage analytics available", ready: "Ready", empty: "Empty",
    noLeadsYet: "No leads yet", noLeadsDescription: "When workspace leads exist, this dashboard will summarize them from FastAPI.",
    loadingDashboard: "Loading dashboard", loadingDashboardData: "Loading dashboard data", unableLoadWorkspaces: "Unable to load your accessible workspaces.",
    dashboardSectionsError: "One or more dashboard sections could not be loaded. No sensitive backend details are shown here.",
    operational: "Operational", humanGovernedAiOperations: "Human-governed AI operations", primaryNavigation: "Primary navigation",
    openNavigation: "Open navigation", closeNavigation: "Close navigation", loadingWorkspaces: "Loading workspaces",
    lastDays: "Last {days} days", loadingAnalytics: "Loading analytics", unableLoadAnalytics: "Unable to load analytics for this workspace.",
    noActivityPeriod: "No activity in this period", noActivityDescription: "No WorkItems, approvals, AI invocations or leads were created in the last {days} days.",
    workItemsCreated: "WorkItems created", successRate: "Success rate", successRateFormula: "Completed ÷ (completed + failed)",
    pendingApprovals: "Pending approvals", approvalRequests: "Approval requests", approvalRequestRate: "Approval request rate",
    approvalRateFormula: "Distinct requested WorkItems ÷ WorkItems created", invocations: "Invocations", tokens: "Tokens",
    knownEstimatedCost: "Known estimated cost", unknownPricingInvocations: "{count} invocation(s) have unknown pricing", persistedAccountingValue: "Persisted accounting value",
    workforceActivity: "Workforce activity", employee: "Employee", success: "Success", capabilityActivity: "Capability activity",
    sales: "Sales", totalLeads: "Total leads", leadsCreated: "Leads created", wonLeads: "Won leads", persistedWonStatus: "Persisted won status",
    leadStatusBreakdown: "Lead status breakdown", noConfiguredActivity: "No configured activity.",
    conversationList: "Conversation list", conversationThread: "Conversation thread", selectConversation: "Select a conversation",
    selectConversationDescription: "Choose a lead from the inbox to inspect workspace-scoped Sales history.", loadingConversations: "Loading conversations",
    unableLoadLeads: "Unable to load workspace leads.", noConversationsYet: "No conversations yet",
    noConversationsDescription: "Leads created in this workspace will appear here in the Sales inbox.", workspaceConversations: "{count} workspace conversations",
    leadListSorted: "Lead list sorted by backend creation time.", backToConversations: "Back to conversations", loadingConversationHistory: "Loading conversation history",
    noMessagesYet: "No messages yet", noMessagesDescription: "The backend has no persisted conversation messages for this lead yet.",
    replyToCustomer: "Reply to customer", replyPlaceholder: "Write the customer message for the backend Sales engine...",
    replyKeyboardHint: "Enter sends. Shift+Enter starts a new line.", sending: "Sending", sendToSales: "Send to Sales", customer: "Customer",
    company: "Company", email: "Email", phone: "Phone", stage: "Stage", humanHandoffRequired: "Human handoff required", reason: "Reason",
    inboxFilters: "Inbox filters", allConversations: "All conversations", humanTakeoverCount: "Human takeover ({count})",
    humanTakeover: "Human takeover", humanTakeoverActive: "Human takeover active", noActiveHandoffs: "No active handoffs",
    noActiveHandoffsDescription: "No Sales conversations currently require a human operator.", assignedOperator: "Assigned operator",
    resolveHandoff: "Resolve handoff", resolvingHandoff: "Resolving", humanReplyToCustomer: "Human reply to customer",
    humanReplyPlaceholder: "Write your final customer-facing message...", humanReplyAuthority: "This message is authored and sent by you. No AI generation is used.",
    sendHumanReply: "Send human reply", humanOperator: "Human operator", humanReplyDelivered: "Human reply delivered",
    handoffRemainsActive: "The handoff remains active until you explicitly resolve it.", humanReplyDeliveryFailed: "The provider did not accept this reply. The handoff remains active.",
    handoffUnavailable: "This handoff is no longer available in the selected workspace.", humanReplyForbidden: "You do not have permission to send human replies.",
    humanReplyConflict: "This reply could not be sent because the handoff, route, or idempotency state changed.", unableSendHumanReply: "Unable to send this human-authored reply.",
    resolveHandoffForbidden: "You do not have permission to resolve this handoff.", resolveHandoffConflict: "This handoff cannot be resolved until its provider route is safe.",
    unableResolveHandoff: "Unable to resolve this handoff.", human_requested: "Customer requested a human",
    unsupported_discount_request: "Unsupported discount request", custom_pricing_required: "Custom pricing required",
    unsupported_commercial_commitment: "Unsupported commercial commitment", authoritative_information_unavailable: "Authoritative information unavailable",
    backendPolicy: "backend policy", createdPendingApproval: "The backend created a pending human approval. No external delivery is implied here.",
    backendSalesReplyGenerated: "Backend Sales reply generated", loadingWorkforce: "Loading AI workforce", unableLoadWorkforce: "Unable to load AI employees for this workspace.",
    noEmployees: "No AI employees configured yet.", noEmployeesDescription: "Persisted employees will appear here when configured for this workspace.",
    noToolAccess: "No integration tool access granted.", noCapabilities: "No capabilities assigned.", loadingWorkItems: "Loading WorkItems",
    unableLoadWorkItems: "Unable to load WorkItems for this workspace.", noWorkItems: "No WorkItems yet.", noWorkItemsDescription: "WorkItems will appear here as HIRI departments create operational work.",
    unassigned: "Unassigned", workItemDetails: "WorkItem details", closeWorkItemDetails: "Close WorkItem details", workItemDetail: "WorkItem detail",
    closeDetails: "Close details", input: "Input", businessResult: "Business result", failure: "Failure", noDataAvailable: "No {section} available.",
    loadingApprovals: "Loading approvals", unableLoadApprovals: "Unable to load approvals for this workspace.", noApprovals: "No approvals waiting for review.",
    noApprovalsDescription: "Approval requests will appear here when HIRI work needs a human decision.", workspaceBusinessAction: "Workspace business action",
    approvalDetails: "Approval details", closeApprovalDetails: "Close approval details", unableRecordDecision: "Unable to record this approval decision.",
    saving: "Saving…", approvalDisclaimer: "Approval authorizes the action; it does not guarantee execution or delivery.",
    approvalRecorded: "Approval recorded. Authorized work may still require backend execution.", rejectionRecorded: "Rejection recorded.",
    noAdditionalData: "No additional data.", none: "None", yes: "Yes", no: "No", approved: "Approved", rejected: "Rejected",
    new: "New", qualified: "Qualified", won: "Won", lost: "Lost", requestedAction: "Requested action", channel: "Channel", lead: "Lead",
    integration: "Integration", requestedAt: "Requested at", reviewerNoteLabel: "Reviewer note", decidedAt: "Decided at", action: "Action", autonomy: "Autonomy", provider: "Provider",
    unknown: "Unknown", conversationUnavailable: "This conversation is unavailable in the selected workspace.", conversationForbidden: "You do not have permission to operate this conversation.",
    unableLoadConversation: "Unable to load this conversation.", leadUnavailable: "This lead is no longer available in the selected workspace.",
    replyForbidden: "You do not have permission to reply in this workspace.", replyConflict: "The backend rejected this reply because of a conversation state conflict.",
    replyRateLimited: "Sales reply generation is currently rate limited. Try again shortly.", unableSendReply: "Unable to send this message to the backend Sales engine.",
    operateConfidence: "Operate your AI workforce with confidence.", structuredWork: "Structured work, human control and operational visibility in one HIRI environment.",
    operatorAccess: "Operator access", signInWorkspace: "Sign in to your workspace", accessEnvironment: "Access the HIRI AI workforce operating environment.",
    emailRequired: "Email is required", validEmail: "Enter a valid email", passwordRequired: "Password is required", invalidCredentials: "Invalid credentials",
    unableSignIn: "Unable to sign in", password: "Password", signingIn: "Signing in", signIn: "Sign in", executed: "Executed",
    discovery: "Discovery", proposal: "Proposal", qualification: "Qualification", correlationId: "Correlation ID", started: "Started",
    approvalStatus: "Approval status", parentWorkItemId: "Parent WorkItem ID", sourceFollowUpTaskId: "Source follow-up task ID", accessActive: "Access active"
  },
  fr: {
    dashboard: "Tableau de bord", inbox: "Boîte commerciale", workforce: "Équipe IA", workItems: "WorkItems",
    approvals: "Approbations", analytics: "Analyses", workspace: "Espace de travail", department: "Département",
    salesDepartment: "Département commercial", operatingSystem: "Système d’exploitation de l’équipe IA",
    lightTheme: "Thème clair", darkTheme: "Thème sombre", switchTheme: "Changer le thème",
    language: "Langue de l’interface", logout: "Se déconnecter", operator: "Opérateur",
    overview: "Vue d’ensemble", commandCenter: "Centre de commande de l’équipe IA",
    commandDescription: "Suivez le travail à traiter, les opérations, l’activité de l’équipe et l’utilisation de l’IA.",
    aiEmployees: "Employés IA", runningWork: "WorkItems en cours", approvalRequired: "Approbation requise",
    failedWork: "WorkItems échoués", recentState: "État opérationnel récent", readiness: "État de préparation",
    conversations: "Conversations", inboxDescription: "Gérez les conversations commerciales et les réponses contrôlées.",
    workforceDescription: "Consultez les employés, capacités, niveaux d’autonomie et accès aux outils.",
    operations: "Opérations", workItemsDescription: "Suivez l’état, l’affectation, les résultats et les échecs.",
    humanReview: "Contrôle humain", approvalsDescription: "Examinez les actions proposées au point de décision humain.",
    analyticsDescription: "Données opérationnelles issues des WorkItems, approbations, coûts IA et ventes.",
    status: "Statut", workType: "Type de travail", aiEmployee: "Employé IA", capability: "Capacité",
    filters: "Filtres", all: "Tous", title: "Titre", updated: "Mis à jour", created: "Créé",
    approve: "Approuver", reject: "Rejeter", reviewDetails: "Examiner", reviewerNote: "Note du réviseur",
    proposedAction: "Action proposée", period: "Période", humanControl: "Contrôle humain",
    aiUsage: "Utilisation de l’IA", cost: "Coût", completed: "Terminé", failed: "Échoué", active: "Actif",
    inactive: "Inactif", enabled: "Activé", disabled: "Désactivé", pending: "en attente",
    createdStatus: "Créé", assigned: "Affecté", running: "En cours", waiting: "En attente",
    approval_required: "Approbation requise", completedStatus: "Terminé", failedStatus: "Échoué",
    cancelled: "Annulé", expired: "Expiré", noWorkspace: "Aucun espace",
    noWorkspaceAvailable: "Aucun espace de travail disponible",
    noWorkspaceDescription: "Créez ou rejoignez un espace de travail avant d’utiliser le tableau de bord opérationnel.",
    configuredWorkforce: "Équipe configurée", currentState: "État actuel", currentWorkItemState: "État actuel des WorkItems",
    safeAggregates: "Agrégats fiables issus de FastAPI, sans données générées.", deliveredActions: "Actions livrées", failedActions: "Actions échouées",
    estimatedAiSpend: "Dépenses IA estimées", workspaceSelected: "Espace de travail sélectionné", integrationAccountActive: "Compte d’intégration actif",
    approvalAnalyticsAvailable: "Analyses des approbations disponibles", aiUsageAnalyticsAvailable: "Analyses de l’utilisation IA disponibles", ready: "Prêt", empty: "Vide",
    noLeadsYet: "Aucun prospect pour le moment", noLeadsDescription: "Lorsque cet espace contiendra des prospects, ce tableau de bord les synthétisera à partir de FastAPI.",
    loadingDashboard: "Chargement du tableau de bord", loadingDashboardData: "Chargement des données du tableau de bord", unableLoadWorkspaces: "Impossible de charger vos espaces de travail accessibles.",
    dashboardSectionsError: "Une ou plusieurs sections du tableau de bord n’ont pas pu être chargées. Aucun détail sensible du backend n’est affiché.",
    operational: "Opérationnel", humanGovernedAiOperations: "Opérations IA sous contrôle humain", primaryNavigation: "Navigation principale",
    openNavigation: "Ouvrir la navigation", closeNavigation: "Fermer la navigation", loadingWorkspaces: "Chargement des espaces de travail",
    lastDays: "{days} derniers jours", loadingAnalytics: "Chargement des analyses", unableLoadAnalytics: "Impossible de charger les analyses de cet espace de travail.",
    noActivityPeriod: "Aucune activité sur cette période", noActivityDescription: "Aucun WorkItem, aucune approbation, aucun appel IA ni prospect n’a été créé au cours des {days} derniers jours.",
    workItemsCreated: "WorkItems créés", successRate: "Taux de réussite", successRateFormula: "Terminés ÷ (terminés + échoués)",
    pendingApprovals: "Approbations en attente", approvalRequests: "Demandes d’approbation", approvalRequestRate: "Taux de demande d’approbation",
    approvalRateFormula: "WorkItems distincts soumis ÷ WorkItems créés", invocations: "Appels", tokens: "Jetons",
    knownEstimatedCost: "Coût estimé connu", unknownPricingInvocations: "{count} appel(s) sans tarif connu", persistedAccountingValue: "Valeur comptable enregistrée",
    workforceActivity: "Activité de l’équipe IA", employee: "Employé", success: "Réussite", capabilityActivity: "Activité par capacité",
    sales: "Ventes", totalLeads: "Prospects au total", leadsCreated: "Prospects créés", wonLeads: "Prospects gagnés", persistedWonStatus: "Statut gagné enregistré",
    leadStatusBreakdown: "Répartition des prospects par statut", noConfiguredActivity: "Aucune activité configurée.",
    conversationList: "Liste des conversations", conversationThread: "Fil de conversation", selectConversation: "Sélectionnez une conversation",
    selectConversationDescription: "Choisissez un prospect dans la boîte de réception pour consulter son historique commercial dans cet espace.", loadingConversations: "Chargement des conversations",
    unableLoadLeads: "Impossible de charger les prospects de cet espace.", noConversationsYet: "Aucune conversation pour le moment",
    noConversationsDescription: "Les prospects créés dans cet espace apparaîtront ici dans la boîte commerciale.", workspaceConversations: "{count} conversations dans l’espace",
    leadListSorted: "Liste des prospects triée par date de création du backend.", backToConversations: "Retour aux conversations", loadingConversationHistory: "Chargement de l’historique de la conversation",
    noMessagesYet: "Aucun message pour le moment", noMessagesDescription: "Le backend ne contient encore aucun message enregistré pour ce prospect.",
    replyToCustomer: "Répondre au client", replyPlaceholder: "Rédigez le message client destiné au moteur commercial du backend...",
    replyKeyboardHint: "Entrée envoie le message. Maj+Entrée insère une nouvelle ligne.", sending: "Envoi", sendToSales: "Envoyer au service commercial", customer: "Client",
    company: "Entreprise", email: "E-mail", phone: "Téléphone", stage: "Étape", humanHandoffRequired: "Transfert à un humain requis", reason: "Motif",
    inboxFilters: "Filtres de la boîte de réception", allConversations: "Toutes les conversations", humanTakeoverCount: "Reprise humaine ({count})",
    humanTakeover: "Reprise humaine", humanTakeoverActive: "Reprise humaine active", noActiveHandoffs: "Aucun transfert actif",
    noActiveHandoffsDescription: "Aucune conversation commerciale ne nécessite actuellement l’intervention d’un opérateur.", assignedOperator: "Opérateur affecté",
    resolveHandoff: "Résoudre le transfert", resolvingHandoff: "Résolution", humanReplyToCustomer: "Réponse humaine au client",
    humanReplyPlaceholder: "Rédigez votre message final destiné au client...", humanReplyAuthority: "Ce message est rédigé et envoyé par vous, sans génération par l’IA.",
    sendHumanReply: "Envoyer la réponse humaine", humanOperator: "Opérateur humain", humanReplyDelivered: "Réponse humaine livrée",
    handoffRemainsActive: "Le transfert reste actif jusqu’à sa résolution explicite.", humanReplyDeliveryFailed: "Le fournisseur n’a pas accepté cette réponse. Le transfert reste actif.",
    handoffUnavailable: "Ce transfert n’est plus disponible dans l’espace sélectionné.", humanReplyForbidden: "Vous n’êtes pas autorisé à envoyer des réponses humaines.",
    humanReplyConflict: "Cette réponse ne peut pas être envoyée, car l’état du transfert, de l’acheminement ou de l’idempotence a changé.", unableSendHumanReply: "Impossible d’envoyer cette réponse rédigée par un humain.",
    resolveHandoffForbidden: "Vous n’êtes pas autorisé à résoudre ce transfert.", resolveHandoffConflict: "Ce transfert ne peut pas être résolu tant que son acheminement fournisseur n’est pas sûr.",
    unableResolveHandoff: "Impossible de résoudre ce transfert.", human_requested: "Le client a demandé un interlocuteur humain",
    unsupported_discount_request: "Demande de remise non prise en charge", custom_pricing_required: "Tarification personnalisée requise",
    unsupported_commercial_commitment: "Engagement commercial non pris en charge", authoritative_information_unavailable: "Information de référence indisponible",
    backendPolicy: "politique du backend", createdPendingApproval: "Le backend a créé une approbation humaine en attente. Cela n’implique aucune livraison externe.",
    backendSalesReplyGenerated: "Réponse commerciale générée par le backend", loadingWorkforce: "Chargement de l’équipe IA", unableLoadWorkforce: "Impossible de charger les employés IA de cet espace.",
    noEmployees: "Aucun employé IA configuré.", noEmployeesDescription: "Les employés enregistrés apparaîtront ici après leur configuration dans cet espace.",
    noToolAccess: "Aucun accès aux outils d’intégration accordé.", noCapabilities: "Aucune capacité attribuée.", loadingWorkItems: "Chargement des WorkItems",
    unableLoadWorkItems: "Impossible de charger les WorkItems de cet espace.", noWorkItems: "Aucun WorkItem pour le moment.", noWorkItemsDescription: "Les WorkItems apparaîtront ici lorsque les départements HIRI créeront du travail opérationnel.",
    unassigned: "Non attribué", workItemDetails: "Détails du WorkItem", closeWorkItemDetails: "Fermer les détails du WorkItem", workItemDetail: "Détail du WorkItem",
    closeDetails: "Fermer les détails", input: "Entrée", businessResult: "Résultat métier", failure: "Échec", noDataAvailable: "Aucune donnée disponible pour « {section} ».",
    loadingApprovals: "Chargement des approbations", unableLoadApprovals: "Impossible de charger les approbations de cet espace.", noApprovals: "Aucune approbation en attente de révision.",
    noApprovalsDescription: "Les demandes d’approbation apparaîtront ici lorsqu’un travail HIRI nécessitera une décision humaine.", workspaceBusinessAction: "Action métier de l’espace",
    approvalDetails: "Détails de l’approbation", closeApprovalDetails: "Fermer les détails de l’approbation", unableRecordDecision: "Impossible d’enregistrer cette décision d’approbation.",
    saving: "Enregistrement…", approvalDisclaimer: "L’approbation autorise l’action, mais ne garantit ni son exécution ni sa livraison.",
    approvalRecorded: "Approbation enregistrée. Le travail autorisé peut encore nécessiter une exécution par le backend.", rejectionRecorded: "Rejet enregistré.",
    noAdditionalData: "Aucune donnée supplémentaire.", none: "Aucun", yes: "Oui", no: "Non", approved: "Approuvé", rejected: "Rejeté",
    new: "Nouveau", qualified: "Qualifié", won: "Gagné", lost: "Perdu", requestedAction: "Action demandée", channel: "Canal", lead: "Prospect",
    integration: "Intégration", requestedAt: "Demandé le", reviewerNoteLabel: "Note du réviseur", decidedAt: "Décidé le", action: "Action", autonomy: "Autonomie", provider: "Fournisseur",
    unknown: "Inconnu", conversationUnavailable: "Cette conversation n’est pas disponible dans l’espace sélectionné.", conversationForbidden: "Vous n’êtes pas autorisé à gérer cette conversation.",
    unableLoadConversation: "Impossible de charger cette conversation.", leadUnavailable: "Ce prospect n’est plus disponible dans l’espace sélectionné.",
    replyForbidden: "Vous n’êtes pas autorisé à répondre dans cet espace.", replyConflict: "Le backend a refusé cette réponse en raison d’un conflit d’état de la conversation.",
    replyRateLimited: "La génération des réponses commerciales est temporairement limitée. Réessayez dans quelques instants.", unableSendReply: "Impossible d’envoyer ce message au moteur commercial du backend.",
    operateConfidence: "Pilotez votre équipe IA en toute confiance.", structuredWork: "Travail structuré, contrôle humain et visibilité opérationnelle réunis dans un environnement HIRI.",
    operatorAccess: "Accès opérateur", signInWorkspace: "Connectez-vous à votre espace de travail", accessEnvironment: "Accédez à l’environnement opérationnel de l’équipe IA HIRI.",
    emailRequired: "L’adresse e-mail est requise", validEmail: "Saisissez une adresse e-mail valide", passwordRequired: "Le mot de passe est requis", invalidCredentials: "Identifiants incorrects",
    unableSignIn: "Impossible de se connecter", password: "Mot de passe", signingIn: "Connexion en cours", signIn: "Se connecter", executed: "Exécuté",
    discovery: "Découverte", proposal: "Proposition", qualification: "Qualification", correlationId: "ID de corrélation", started: "Démarré",
    approvalStatus: "Statut d’approbation", parentWorkItemId: "ID du WorkItem parent", sourceFollowUpTaskId: "ID de la tâche de suivi source", accessActive: "Accès actif"
  },
  ar: {
    dashboard: "لوحة التحكم", inbox: "صندوق وارد المبيعات", workforce: "القوى العاملة بالذكاء الاصطناعي", workItems: "مهام العمل",
    approvals: "الموافقات", analytics: "التحليلات", workspace: "مساحة العمل", department: "القسم",
    salesDepartment: "قسم المبيعات", operatingSystem: "نظام تشغيل القوى العاملة بالذكاء الاصطناعي",
    lightTheme: "الوضع الفاتح", darkTheme: "الوضع الداكن", switchTheme: "تبديل مظهر الألوان",
    language: "لغة الواجهة", logout: "تسجيل الخروج", operator: "المشغّل",
    overview: "نظرة عامة", commandCenter: "مركز قيادة القوى العاملة بالذكاء الاصطناعي",
    commandDescription: "راقب العمل الذي يتطلب الانتباه والعمليات الحالية ونشاط القوى العاملة واستخدام الذكاء الاصطناعي.",
    aiEmployees: "موظفو الذكاء الاصطناعي", runningWork: "مهام قيد التنفيذ", approvalRequired: "يتطلب الموافقة",
    failedWork: "مهام فاشلة", recentState: "الحالة التشغيلية الأخيرة", readiness: "جاهزية مساحة العمل",
    conversations: "المحادثات", inboxDescription: "إدارة محادثات المبيعات والردود الخاضعة للتحكم.",
    workforceDescription: "استعراض الموظفين والقدرات والاستقلالية والوصول المعتمد للأدوات.",
    operations: "العمليات", workItemsDescription: "تتبع حالة العمل والإسناد والنتائج والإخفاقات.",
    humanReview: "المراجعة البشرية", approvalsDescription: "مراجعة إجراءات العمل المقترحة عند نقطة القرار البشري.",
    analyticsDescription: "حقائق تشغيلية من مهام العمل والموافقات ومحاسبة الذكاء الاصطناعي والمبيعات.",
    status: "الحالة", workType: "نوع العمل", aiEmployee: "موظف ذكاء اصطناعي", capability: "القدرة",
    filters: "عوامل التصفية", all: "الكل", title: "العنوان", updated: "آخر تحديث", created: "تم الإنشاء",
    approve: "موافقة", reject: "رفض", reviewDetails: "مراجعة التفاصيل", reviewerNote: "ملاحظة المراجع",
    proposedAction: "الإجراء المقترح", period: "الفترة", humanControl: "التحكم البشري",
    aiUsage: "استخدام الذكاء الاصطناعي", cost: "التكلفة", completed: "مكتمل", failed: "فشل", active: "نشط",
    inactive: "غير نشط", enabled: "مفعّل", disabled: "معطّل", pending: "قيد الانتظار",
    createdStatus: "تم الإنشاء", assigned: "تم الإسناد", running: "قيد التنفيذ", waiting: "في الانتظار",
    approval_required: "يتطلب الموافقة", completedStatus: "مكتمل", failedStatus: "فشل",
    cancelled: "ملغى", expired: "منتهي الصلاحية", noWorkspace: "لا توجد مساحة عمل",
    noWorkspaceAvailable: "لا توجد مساحة عمل متاحة",
    noWorkspaceDescription: "أنشئ مساحة عمل أو انضم إليها قبل استخدام لوحة التحكم التشغيلية.",
    configuredWorkforce: "القوى العاملة المهيأة", currentState: "الحالة الحالية", currentWorkItemState: "الحالة الحالية لمهام WorkItem",
    safeAggregates: "بيانات مجمّعة موثوقة من FastAPI وليست حقائق مولّدة.", deliveredActions: "الإجراءات المنفّذة", failedActions: "الإجراءات الفاشلة",
    estimatedAiSpend: "الإنفاق التقديري على الذكاء الاصطناعي", workspaceSelected: "تم تحديد مساحة العمل", integrationAccountActive: "حساب التكامل نشط",
    approvalAnalyticsAvailable: "تحليلات الموافقات متاحة", aiUsageAnalyticsAvailable: "تحليلات استخدام الذكاء الاصطناعي متاحة", ready: "جاهز", empty: "فارغ",
    noLeadsYet: "لا يوجد عملاء محتملون بعد", noLeadsDescription: "عند توفر عملاء محتملين في مساحة العمل، ستعرض لوحة التحكم ملخصًا لهم من FastAPI.",
    loadingDashboard: "جارٍ تحميل لوحة التحكم", loadingDashboardData: "جارٍ تحميل بيانات لوحة التحكم", unableLoadWorkspaces: "تعذر تحميل مساحات العمل المتاحة لك.",
    dashboardSectionsError: "تعذر تحميل قسم واحد أو أكثر من لوحة التحكم. لا تُعرض هنا أي تفاصيل حساسة من الواجهة الخلفية.",
    operational: "قيد التشغيل", humanGovernedAiOperations: "عمليات ذكاء اصطناعي بإشراف بشري", primaryNavigation: "التنقل الرئيسي",
    openNavigation: "فتح قائمة التنقل", closeNavigation: "إغلاق قائمة التنقل", loadingWorkspaces: "جارٍ تحميل مساحات العمل",
    lastDays: "آخر {days} يومًا", loadingAnalytics: "جارٍ تحميل التحليلات", unableLoadAnalytics: "تعذر تحميل تحليلات مساحة العمل هذه.",
    noActivityPeriod: "لا يوجد نشاط خلال هذه الفترة", noActivityDescription: "لم يتم إنشاء أي WorkItems أو موافقات أو استدعاءات للذكاء الاصطناعي أو عملاء محتملين خلال آخر {days} يومًا.",
    workItemsCreated: "WorkItems المنشأة", successRate: "معدل النجاح", successRateFormula: "المكتملة ÷ (المكتملة + الفاشلة)",
    pendingApprovals: "الموافقات المعلّقة", approvalRequests: "طلبات الموافقة", approvalRequestRate: "معدل طلب الموافقة",
    approvalRateFormula: "WorkItems المميزة المطلوبة ÷ WorkItems المنشأة", invocations: "الاستدعاءات", tokens: "الرموز المميزة",
    knownEstimatedCost: "التكلفة التقديرية المعروفة", unknownPricingInvocations: "{count} استدعاء بسعر غير معروف", persistedAccountingValue: "قيمة محاسبية محفوظة",
    workforceActivity: "نشاط القوى العاملة", employee: "الموظف", success: "النجاح", capabilityActivity: "النشاط حسب القدرة",
    sales: "المبيعات", totalLeads: "إجمالي العملاء المحتملين", leadsCreated: "العملاء المحتملون المنشؤون", wonLeads: "العملاء المحتملون المكتسبون", persistedWonStatus: "حالة الفوز المحفوظة",
    leadStatusBreakdown: "توزيع حالات العملاء المحتملين", noConfiguredActivity: "لا يوجد نشاط مهيأ.",
    conversationList: "قائمة المحادثات", conversationThread: "سجل المحادثة", selectConversation: "حدد محادثة",
    selectConversationDescription: "اختر عميلًا محتملًا من صندوق الوارد لاستعراض سجل المبيعات الخاص بمساحة العمل.", loadingConversations: "جارٍ تحميل المحادثات",
    unableLoadLeads: "تعذر تحميل العملاء المحتملين في مساحة العمل.", noConversationsYet: "لا توجد محادثات بعد",
    noConversationsDescription: "سيظهر هنا العملاء المحتملون المنشؤون في مساحة العمل ضمن صندوق وارد المبيعات.", workspaceConversations: "{count} محادثة في مساحة العمل",
    leadListSorted: "قائمة العملاء المحتملين مرتبة حسب وقت الإنشاء في الواجهة الخلفية.", backToConversations: "العودة إلى المحادثات", loadingConversationHistory: "جارٍ تحميل سجل المحادثة",
    noMessagesYet: "لا توجد رسائل بعد", noMessagesDescription: "لا تحتوي الواجهة الخلفية حتى الآن على رسائل محادثة محفوظة لهذا العميل المحتمل.",
    replyToCustomer: "الرد على العميل", replyPlaceholder: "اكتب رسالة العميل لإرسالها إلى محرك المبيعات في الواجهة الخلفية...",
    replyKeyboardHint: "اضغط Enter للإرسال وShift+Enter لسطر جديد.", sending: "جارٍ الإرسال", sendToSales: "إرسال إلى المبيعات", customer: "العميل",
    company: "الشركة", email: "البريد الإلكتروني", phone: "الهاتف", stage: "المرحلة", humanHandoffRequired: "يلزم التحويل إلى موظف بشري", reason: "السبب",
    inboxFilters: "مرشحات صندوق الوارد", allConversations: "كل المحادثات", humanTakeoverCount: "تولٍ بشري ({count})",
    humanTakeover: "تولٍ بشري", humanTakeoverActive: "التولي البشري نشط", noActiveHandoffs: "لا توجد تحويلات نشطة",
    noActiveHandoffsDescription: "لا توجد محادثات مبيعات تتطلب تدخل مشغّل بشري حاليًا.", assignedOperator: "المشغّل المسند إليه",
    resolveHandoff: "إنهاء التحويل", resolvingHandoff: "جارٍ الإنهاء", humanReplyToCustomer: "رد بشري على العميل",
    humanReplyPlaceholder: "اكتب رسالتك النهائية الموجهة إلى العميل...", humanReplyAuthority: "هذه الرسالة من صياغتك وإرسالك، ولا يُستخدم الذكاء الاصطناعي لإنشائها.",
    sendHumanReply: "إرسال الرد البشري", humanOperator: "مشغّل بشري", humanReplyDelivered: "تم تسليم الرد البشري",
    handoffRemainsActive: "يظل التحويل نشطًا حتى تنهيه صراحةً.", humanReplyDeliveryFailed: "لم يقبل المزوّد هذا الرد. يظل التحويل نشطًا.",
    handoffUnavailable: "لم يعد هذا التحويل متاحًا في مساحة العمل المحددة.", humanReplyForbidden: "ليست لديك صلاحية إرسال ردود بشرية.",
    humanReplyConflict: "تعذر إرسال هذا الرد بسبب تغير حالة التحويل أو مسار الإرسال أو مفتاح منع التكرار.", unableSendHumanReply: "تعذر إرسال هذا الرد البشري.",
    resolveHandoffForbidden: "ليست لديك صلاحية إنهاء هذا التحويل.", resolveHandoffConflict: "لا يمكن إنهاء هذا التحويل قبل التأكد من سلامة مسار المزوّد.",
    unableResolveHandoff: "تعذر إنهاء هذا التحويل.", human_requested: "طلب العميل التحدث إلى موظف بشري",
    unsupported_discount_request: "طلب خصم غير مدعوم", custom_pricing_required: "يلزم تسعير مخصص",
    unsupported_commercial_commitment: "التزام تجاري غير مدعوم", authoritative_information_unavailable: "المعلومات المرجعية غير متاحة",
    backendPolicy: "سياسة الواجهة الخلفية", createdPendingApproval: "أنشأت الواجهة الخلفية موافقة بشرية معلّقة. لا يعني ذلك تنفيذ أي تسليم خارجي.",
    backendSalesReplyGenerated: "تم إنشاء رد المبيعات في الواجهة الخلفية", loadingWorkforce: "جارٍ تحميل القوى العاملة بالذكاء الاصطناعي", unableLoadWorkforce: "تعذر تحميل موظفي الذكاء الاصطناعي في مساحة العمل.",
    noEmployees: "لم تتم تهيئة أي موظف ذكاء اصطناعي بعد.", noEmployeesDescription: "سيظهر الموظفون المحفوظون هنا بعد تهيئتهم لمساحة العمل.",
    noToolAccess: "لم يُمنح أي وصول إلى أدوات التكامل.", noCapabilities: "لم تُسند أي قدرات.", loadingWorkItems: "جارٍ تحميل WorkItems",
    unableLoadWorkItems: "تعذر تحميل WorkItems لمساحة العمل.", noWorkItems: "لا توجد WorkItems بعد.", noWorkItemsDescription: "ستظهر WorkItems هنا عندما تنشئ أقسام HIRI أعمالًا تشغيلية.",
    unassigned: "غير مسند", workItemDetails: "تفاصيل WorkItem", closeWorkItemDetails: "إغلاق تفاصيل WorkItem", workItemDetail: "تفاصيل WorkItem",
    closeDetails: "إغلاق التفاصيل", input: "المدخلات", businessResult: "نتيجة العمل", failure: "فشل", noDataAvailable: "لا تتوفر بيانات لقسم «{section}».",
    loadingApprovals: "جارٍ تحميل الموافقات", unableLoadApprovals: "تعذر تحميل موافقات مساحة العمل.", noApprovals: "لا توجد موافقات بانتظار المراجعة.",
    noApprovalsDescription: "ستظهر طلبات الموافقة هنا عندما يتطلب عمل HIRI قرارًا بشريًا.", workspaceBusinessAction: "إجراء عمل في مساحة العمل",
    approvalDetails: "تفاصيل الموافقة", closeApprovalDetails: "إغلاق تفاصيل الموافقة", unableRecordDecision: "تعذر تسجيل قرار الموافقة هذا.",
    saving: "جارٍ الحفظ…", approvalDisclaimer: "تسمح الموافقة بتنفيذ الإجراء، لكنها لا تضمن تنفيذه أو تسليمه.",
    approvalRecorded: "تم تسجيل الموافقة. قد يظل العمل المصرح به بحاجة إلى تنفيذ من الواجهة الخلفية.", rejectionRecorded: "تم تسجيل الرفض.",
    noAdditionalData: "لا توجد بيانات إضافية.", none: "لا شيء", yes: "نعم", no: "لا", approved: "مقبول", rejected: "مرفوض",
    new: "جديد", qualified: "مؤهل", won: "مكتسب", lost: "مفقود", requestedAction: "الإجراء المطلوب", channel: "القناة", lead: "العميل المحتمل",
    integration: "التكامل", requestedAt: "وقت الطلب", reviewerNoteLabel: "ملاحظة المراجع", decidedAt: "وقت القرار", action: "الإجراء", autonomy: "الاستقلالية", provider: "المزوّد",
    unknown: "غير معروف", conversationUnavailable: "هذه المحادثة غير متاحة في مساحة العمل المحددة.", conversationForbidden: "ليست لديك صلاحية إدارة هذه المحادثة.",
    unableLoadConversation: "تعذر تحميل هذه المحادثة.", leadUnavailable: "لم يعد هذا العميل المحتمل متاحًا في مساحة العمل المحددة.",
    replyForbidden: "ليست لديك صلاحية الرد في مساحة العمل هذه.", replyConflict: "رفضت الواجهة الخلفية هذا الرد بسبب تعارض في حالة المحادثة.",
    replyRateLimited: "معدل إنشاء ردود المبيعات محدود حاليًا. حاول مجددًا بعد قليل.", unableSendReply: "تعذر إرسال هذه الرسالة إلى محرك المبيعات في الواجهة الخلفية.",
    operateConfidence: "أدِر قواك العاملة بالذكاء الاصطناعي بثقة.", structuredWork: "عمل منظم وتحكم بشري ورؤية تشغيلية في بيئة HIRI واحدة.",
    operatorAccess: "دخول المشغّل", signInWorkspace: "سجّل الدخول إلى مساحة عملك", accessEnvironment: "ادخل إلى بيئة تشغيل القوى العاملة بالذكاء الاصطناعي في HIRI.",
    emailRequired: "البريد الإلكتروني مطلوب", validEmail: "أدخل بريدًا إلكترونيًا صالحًا", passwordRequired: "كلمة المرور مطلوبة", invalidCredentials: "بيانات الاعتماد غير صحيحة",
    unableSignIn: "تعذر تسجيل الدخول", password: "كلمة المرور", signingIn: "جارٍ تسجيل الدخول", signIn: "تسجيل الدخول", executed: "تم التنفيذ",
    discovery: "الاستكشاف", proposal: "العرض", qualification: "التأهيل", correlationId: "معرّف الارتباط", started: "بدأ",
    approvalStatus: "حالة الموافقة", parentWorkItemId: "معرّف WorkItem الأصل", sourceFollowUpTaskId: "معرّف مهمة المتابعة المصدر", accessActive: "الوصول نشط"
  }
};

const publicMessages: Record<AppLocale, Record<string, string>> = {
  en: {
    publicNavigation: "Public navigation", mobileNavigation: "Mobile navigation", skipContent: "Skip to content",
    platformNav: "Platform", howItWorksNav: "How it works", salesNav: "Sales", aboutNav: "About",
    contactNav: "Contact", loginAction: "Log in", createAccount: "Create account", openPublicNavigation: "Open navigation",
    closePublicNavigation: "Close navigation", productLabel: "AI Workforce Platform", homepageTitle: "Hire your AI workforce.",
    homepageDescription: "Build AI employees, specialized teams and departments that perform real business work—with permissions, approvals, cost control and auditability.",
    explorePlatform: "Explore the platform", permissionAware: "Permission-aware", humanGoverned: "Human-governed", businessReady: "Business-ready",
    footerStatement: "The operating system for your AI workforce.", footerDescription: "AI employees and departments performing real business work with human control.",
    product: "Product", companyLabel: "Company", accessLabel: "Access", footerControl: "AI workforce. Human control.",
    platformPageTitle: "A controlled platform for AI business work", platformPageDescription: "Organize AI employees, capabilities, tools, permissions and WorkItems within one accountable operating structure.",
    howPageTitle: "From business request to accountable result", howPageDescription: "HIRI turns business demand into governed WorkItems, assigns eligible AI employees and records outcomes for review.",
    salesPageTitle: "Operate Sales work through specialized AI employees", salesPageDescription: "Coordinate lead handling, conversations and follow-up while approvals and permissions keep sensitive actions controlled.",
    aboutPageTitle: "Built for accountable AI operations", aboutPageDescription: "HIRI is an AI Workforce Platform designed around clear ownership, human control and operational visibility.",
    contactPageTitle: "Talk with HIRI", contactPageDescription: "Contact the HIRI team to discuss how an AI workforce could fit your operating model.",
    foundationLabel: "Phase 1 foundation", foundationNote: "Detailed page content and final visual composition will follow in Phase 2.",
    registerTitle: "Create your HIRI account", registerDescription: "Set up your operator identity, then continue into your workspace environment.",
    displayName: "Display name", displayNameRequired: "Display name is required", passwordMinimum: "Use at least 12 characters",
    confirmPassword: "Confirm password", passwordsMismatch: "Passwords do not match", creatingAccount: "Creating account",
    accountExists: "An account with this email already exists", unableCreateAccount: "Unable to create your account",
    alreadyHaveAccount: "Already have an account?", needAccount: "Need an account?", authFoundation: "HIRI operator access",
    authStatement: "Secure access to your AI workforce operating environment."
  },
  fr: {
    publicNavigation: "Navigation publique", mobileNavigation: "Navigation mobile", skipContent: "Aller au contenu",
    platformNav: "Plateforme", howItWorksNav: "Fonctionnement", salesNav: "Ventes", aboutNav: "À propos",
    contactNav: "Contact", loginAction: "Se connecter", createAccount: "Créer un compte", openPublicNavigation: "Ouvrir la navigation",
    closePublicNavigation: "Fermer la navigation", productLabel: "Plateforme de workforce IA", homepageTitle: "Constituez votre workforce IA.",
    homepageDescription: "Créez des employés IA, des équipes spécialisées et des départements qui réalisent un véritable travail métier, avec permissions, approbations, contrôle des coûts et traçabilité.",
    explorePlatform: "Découvrir la plateforme", permissionAware: "Permissions intégrées", humanGoverned: "Sous contrôle humain", businessReady: "Prêt pour l’entreprise",
    footerStatement: "Le système d’exploitation de votre workforce IA.", footerDescription: "Des employés et départements IA qui réalisent un travail métier réel sous contrôle humain.",
    product: "Produit", companyLabel: "Entreprise", accessLabel: "Accès", footerControl: "Workforce IA. Contrôle humain.",
    platformPageTitle: "Une plateforme maîtrisée pour le travail métier assisté par IA", platformPageDescription: "Organisez employés IA, capacités, outils, permissions et WorkItems dans une structure opérationnelle responsable.",
    howPageTitle: "De la demande métier au résultat traçable", howPageDescription: "HIRI transforme la demande en WorkItems gouvernés, les attribue aux employés IA compétents et enregistre les résultats pour révision.",
    salesPageTitle: "Pilotez les ventes avec des employés IA spécialisés", salesPageDescription: "Coordonnez le traitement des prospects, les conversations et les relances tout en contrôlant les actions sensibles par des permissions et approbations.",
    aboutPageTitle: "Conçu pour des opérations IA responsables", aboutPageDescription: "HIRI est une plateforme de workforce IA fondée sur la responsabilité, le contrôle humain et la visibilité opérationnelle.",
    contactPageTitle: "Échangez avec HIRI", contactPageDescription: "Contactez l’équipe HIRI pour étudier l’intégration d’une workforce IA à votre modèle opérationnel.",
    foundationLabel: "Fondation de la phase 1", foundationNote: "Le contenu détaillé et la composition visuelle finale seront réalisés en phase 2.",
    registerTitle: "Créez votre compte HIRI", registerDescription: "Configurez votre identité d’opérateur, puis accédez à votre environnement de travail.",
    displayName: "Nom affiché", displayNameRequired: "Le nom affiché est requis", passwordMinimum: "Utilisez au moins 12 caractères",
    confirmPassword: "Confirmer le mot de passe", passwordsMismatch: "Les mots de passe ne correspondent pas", creatingAccount: "Création du compte",
    accountExists: "Un compte existe déjà avec cette adresse e-mail", unableCreateAccount: "Impossible de créer votre compte",
    alreadyHaveAccount: "Vous avez déjà un compte ?", needAccount: "Besoin d’un compte ?", authFoundation: "Accès opérateur HIRI",
    authStatement: "Accès sécurisé à votre environnement opérationnel de workforce IA."
  },
  ar: {
    publicNavigation: "التنقل العام", mobileNavigation: "التنقل عبر الهاتف", skipContent: "الانتقال إلى المحتوى",
    platformNav: "المنصة", howItWorksNav: "آلية العمل", salesNav: "المبيعات", aboutNav: "حول HIRI",
    contactNav: "تواصل معنا", loginAction: "تسجيل الدخول", createAccount: "إنشاء حساب", openPublicNavigation: "فتح قائمة التنقل",
    closePublicNavigation: "إغلاق قائمة التنقل", productLabel: "منصة القوى العاملة بالذكاء الاصطناعي", homepageTitle: "وظّف قواك العاملة بالذكاء الاصطناعي.",
    homepageDescription: "أنشئ موظفين وفرقًا متخصصة وأقسامًا بالذكاء الاصطناعي تنفذ أعمالًا حقيقية، ضمن صلاحيات وموافقات وضوابط تكلفة وسجل قابل للتدقيق.",
    explorePlatform: "استكشف المنصة", permissionAware: "مدرك للصلاحيات", humanGoverned: "بإشراف بشري", businessReady: "جاهز للأعمال",
    footerStatement: "نظام تشغيل قواك العاملة بالذكاء الاصطناعي.", footerDescription: "موظفون وأقسام بالذكاء الاصطناعي ينفذون أعمالًا حقيقية تحت إشراف بشري.",
    product: "المنتج", companyLabel: "الشركة", accessLabel: "الدخول", footerControl: "قوى عاملة ذكية. تحكم بشري.",
    platformPageTitle: "منصة منضبطة لأعمال الذكاء الاصطناعي", platformPageDescription: "نظّم الموظفين والقدرات والأدوات والصلاحيات وWorkItems ضمن هيكل تشغيلي واضح المسؤولية.",
    howPageTitle: "من طلب العمل إلى نتيجة قابلة للمساءلة", howPageDescription: "تحوّل HIRI احتياجات العمل إلى WorkItems محكومة، وتسندها إلى موظفي الذكاء الاصطناعي المؤهلين، وتسجل النتائج للمراجعة.",
    salesPageTitle: "أدِر أعمال المبيعات بموظفين متخصصين بالذكاء الاصطناعي", salesPageDescription: "نسّق معالجة العملاء المحتملين والمحادثات والمتابعة مع إبقاء الإجراءات الحساسة تحت تحكم الصلاحيات والموافقات.",
    aboutPageTitle: "مصممة لعمليات ذكاء اصطناعي خاضعة للمساءلة", aboutPageDescription: "HIRI منصة للقوى العاملة بالذكاء الاصطناعي ترتكز على وضوح المسؤولية والتحكم البشري والرؤية التشغيلية.",
    contactPageTitle: "تواصل مع HIRI", contactPageDescription: "تواصل مع فريق HIRI لمناقشة ملاءمة القوى العاملة بالذكاء الاصطناعي لنموذجك التشغيلي.",
    foundationLabel: "أساس المرحلة الأولى", foundationNote: "سيُستكمل المحتوى التفصيلي والتكوين البصري النهائي في المرحلة الثانية.",
    registerTitle: "أنشئ حسابك في HIRI", registerDescription: "أنشئ هوية المشغّل ثم انتقل إلى بيئة مساحة عملك.",
    displayName: "الاسم المعروض", displayNameRequired: "الاسم المعروض مطلوب", passwordMinimum: "استخدم 12 حرفًا على الأقل",
    confirmPassword: "تأكيد كلمة المرور", passwordsMismatch: "كلمتا المرور غير متطابقتين", creatingAccount: "جارٍ إنشاء الحساب",
    accountExists: "يوجد حساب مسجل بهذا البريد الإلكتروني", unableCreateAccount: "تعذر إنشاء حسابك",
    alreadyHaveAccount: "لديك حساب بالفعل؟", needAccount: "تحتاج إلى حساب؟", authFoundation: "دخول مشغّل HIRI",
    authStatement: "وصول آمن إلى بيئة تشغيل قواك العاملة بالذكاء الاصطناعي."
  }
};

type ExperienceValue = {
  theme: AppTheme;
  locale: AppLocale;
  direction: "ltr" | "rtl";
  setTheme: (theme: AppTheme) => void;
  setLocale: (locale: AppLocale) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
};

const ExperienceContext = createContext<ExperienceValue | null>(null);

function initialTheme(): AppTheme {
  const saved = localStorage.getItem("hiri-theme");
  if (saved === "light" || saved === "dark") return saved;
  return globalThis.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

function initialLocale(): AppLocale {
  const saved = localStorage.getItem("hiri-locale");
  return saved === "fr" || saved === "ar" ? saved : "en";
}

export function AppExperienceProvider({ children }: { children: React.ReactNode }) {
  const [theme, updateTheme] = useState<AppTheme>(initialTheme);
  const [locale, updateLocale] = useState<AppLocale>(initialLocale);
  const direction = locale === "ar" ? "rtl" : "ltr";
  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = direction;
    document.documentElement.dataset.hiriTheme = theme;
  }, [direction, locale, theme]);
  const value = useMemo<ExperienceValue>(() => ({
    theme,
    locale,
    direction,
    setTheme: (next) => { localStorage.setItem("hiri-theme", next); updateTheme(next); },
    setLocale: (next) => { localStorage.setItem("hiri-locale", next); updateLocale(next); },
    t: (key, values = {}) => Object.entries(values).reduce(
      (message, [name, replacement]) => message.replaceAll(`{${name}}`, String(replacement)),
      publicMessages[locale][key] ?? messages[locale][key] ?? publicMessages.en[key] ?? messages.en[key] ?? key
    )
  }), [direction, locale, theme]);
  return <ExperienceContext.Provider value={value}>{children}</ExperienceContext.Provider>;
}

export function useAppExperience() {
  const value = useContext(ExperienceContext);
  if (!value) throw new Error("useAppExperience must be used inside AppExperienceProvider");
  return value;
}
