import { useAppExperience } from "./AppExperience";

const en = {
  common: {
    create: "Create account", how: "See how it works", platform: "Explore the platform", sales: "Explore HIRI Sales",
    controlled: "Controlled execution", result: "Business result", approval: "Approval if required", audit: "Audit and analytics",
    finalTitle: "Build your AI workforce.", finalCopy: "Start with one focused employee. Expand when your operating model is ready.",
    workItem: "WorkItem", employee: "AI employee", tool: "Allowed tool", event: "Business event"
  },
  home: {
    eyebrow: "AI Workforce Platform", title: "Hire your AI workforce.",
    lead: "AI employees that perform real business work using company tools, data and communication channels—governed by permissions, approvals, cost control and auditability.",
    visualTitle: "Governed execution", request: "Inbound sales request", assigned: "Sales Qualification", permission: "CRM access allowed", output: "Qualified opportunity recorded",
    whatLabel: "What HIRI is", whatTitle: "One platform. AI employees. Real business execution.",
    whatCopy: "Build the workforce in deliberate stages without losing ownership, context or control.",
    levels: [
      ["01", "One AI employee", "A focused role with instructions, capabilities and approved access."],
      ["02", "Specialized AI team", "Several employees coordinated around a shared business outcome."],
      ["03", "AI department", "Repeatable work supervised within one operational function."],
      ["04", "Coordinated departments", "A shared operating model across the company as it matures."]
    ],
    flowLabel: "How work moves", flowTitle: "From demand to an accountable result.",
    flowCopy: "Every meaningful unit of execution can become a WorkItem: visible, assigned, governed and reviewable.",
    flow: ["Business event", "WorkItem", "Right AI employee", "Allowed capability and tool", "Approval if required", "Business result", "Audit"],
    salesLabel: "Sales first", salesTitle: "A mature starting point for the AI workforce.",
    salesCopy: "HIRI Sales is designed to capture buying intent, understand context and keep qualified work moving under business rules.",
    salesFlow: ["Capture", "Understand", "Qualify", "Converse", "Follow up", "Convert"],
    channelsLabel: "Designed to connect with channels such as", channels: ["Website", "Facebook", "Instagram", "WhatsApp", "Email", "Forms", "APIs and webhooks"],
    controlLabel: "Human control", controlTitle: "Authority should be earned, not assumed.",
    controlCopy: "HIRI gives each employee only the capabilities, tools and autonomy its role requires. Sensitive work can stop at a human decision boundary.",
    controls: [["Permissions", "Define what the employee may do."], ["Policies", "Apply business rules before action."], ["Approvals", "Keep people at consequential decisions."], ["Allowed tools", "Limit external execution surfaces."], ["Audit history", "Preserve a reviewable record."], ["Usage and cost", "Observe model consumption in context."]],
    platformLabel: "Platform preview", platformTitle: "The operating layer behind every employee.",
    areas: [["AI Workforce", "Roles and capabilities"], ["WorkItems", "Owned units of work"], ["Approvals", "Human decision points"], ["Integrations", "Governed tool access"], ["AI Gateway", "Models, usage and cost"], ["Audit / Analytics", "Operational visibility"]]
  },
  platform: {
    eyebrow: "Platform", title: "The operating system for an AI workforce.",
    lead: "HIRI coordinates employees, work, permissions, tools and results in one controlled operating structure.",
    workforceLabel: "AI workforce", workforceTitle: "Every employee has an explicit operating identity.",
    workforceCopy: "Departments define ownership. Supervisors coordinate the work. Specialist employees execute only through the capabilities and access assigned to them.",
    employeeFields: [["Role", "What the employee is responsible for"], ["Instructions", "How work should be handled"], ["Capabilities", "Which business skills are available"], ["Tool access", "Which external systems may be used"], ["Permissions", "Where authority starts and stops"], ["Knowledge", "Which company context is available"], ["Autonomy", "When a person must decide"], ["Metrics", "How activity and outcomes are observed"]],
    workLabel: "WorkItem execution", workTitle: "One universal unit of visible work.",
    workCopy: "A WorkItem carries ownership, state, inputs, approvals and results through a reviewable lifecycle.",
    lifecycle: ["Created", "Assigned", "Running", "Waiting or approval required", "Completed"], exceptions: "Failed, cancelled and expired states keep exceptions explicit.",
    govLabel: "Governance", govTitle: "Autonomy inside a defined boundary.",
    autonomy: [["1", "Suggest", "HIRI recommends; a person acts."], ["2", "Draft + human approval", "HIRI prepares; a person authorizes."], ["3", "Controlled automation", "HIRI acts through explicit permissions."], ["4", "High automation", "HIRI operates within a narrow approved boundary."]],
    guardrails: ["Permissions", "Policies", "Allowed tools", "Approvals", "Audit history"],
    connectLabel: "Connectivity", connectTitle: "External tools execute allowed actions.",
    connectCopy: "HIRI is designed to connect with business channels and systems while keeping decision and WorkItem state inside HIRI. Availability depends on the configured integration.",
    connections: ["Meta", "WhatsApp", "Gmail", "Outlook", "Google Calendar", "CRM", "Shopify", "WooCommerce", "Slack", "APIs", "Webhooks", "MCP", "n8n"],
    gatewayLabel: "AI Gateway", gatewayTitle: "Models remain replaceable. Usage remains observable.",
    gatewayCopy: "A shared gateway can abstract providers, route models, apply quotas and fallbacks, and record usage, cost and operational logs.",
    gatewayItems: ["Provider abstraction", "Model routing", "Usage and cost tracking", "Quotas and fallbacks", "Logging and observability"],
    contextLabel: "Shared business context", contextTitle: "Departments work from the same business reality.",
    contextCopy: "HIRI reuses shared business objects instead of creating a disconnected customer system for every department.",
    objects: ["Customer", "Lead", "Contact", "Conversation", "Product", "Order", "Invoice", "Ticket", "WorkItem"]
  },
  how: {
    eyebrow: "How it works", title: "From business event to governed execution.",
    lead: "HIRI turns incoming work into a controlled chain of ownership, capability, permission and result.",
    processLabel: "Execution model", processTitle: "Twelve checks, one understandable path.",
    steps: [["01", "Work enters HIRI", "A message, event or scheduled need creates demand."], ["02", "Workspace identified", "The work stays inside the correct company boundary."], ["03", "Department owns it", "A business function becomes accountable for the outcome."], ["04", "Supervisor routes it", "Coordination selects the appropriate operating path."], ["05", "Specialist selected", "An eligible AI employee receives the work."], ["06", "Capability resolved", "HIRI confirms the required business skill."], ["07", "Allowed tool checked", "Only approved execution surfaces are considered."], ["08", "Policies enforced", "Permissions and business rules are evaluated."], ["09", "WorkItem executes", "Inputs, state and progress remain visible."], ["10", "Human approval", "Consequential actions pause when required."], ["11", "Result produced", "The business outcome is recorded."], ["12", "History updated", "Audit and analytics retain the operating record."]],
    differenceLabel: "Controlled by design", differenceTitle: "More accountable than an unrestricted agent.",
    unrestricted: "Unrestricted agent", unrestrictedCopy: "Broad access and loosely bounded action make ownership and review difficult.",
    hiriModel: "HIRI execution", formula: ["Role", "Capability", "Allowed tool", "Permission", "Policy", "Approval", "Audit"],
    boundaryTitle: "Human control where it matters.", boundaryCopy: "Routine work can progress inside policy. Sensitive external actions can pause with the exact WorkItem, requester, proposed action and consequence visible to a reviewer."
  },
  sales: {
    eyebrow: "HIRI Sales", title: "AI sales employees for governed revenue work.",
    lead: "Handle inbound buying intent, qualification, conversation and follow-up through specialized employees operating within your business rules.",
    flow: ["Capture", "Understand", "Qualify", "Converse", "Follow up", "Convert"],
    captureLabel: "Lead capture", captureTitle: "Turn signals of intent into structured work.",
    captureCopy: "HIRI Sales is designed to connect with inbound sources such as social channels, websites, forms, email, ads and APIs. Integration availability depends on configuration.",
    sources: ["Facebook", "Instagram", "WhatsApp", "Website", "Forms", "Email", "Ads and landing pages", "APIs and webhooks"],
    intentFlow: ["Prospect shows intent", "Lead created or matched", "Context understood", "Qualification begins"],
    stages: [["Qualification", "Apply your business criteria to intent, fit, need and context without inventing unsupported scores."], ["Sales conversation", "Specialist employees respond with relevant context while a person can take over when needed."], ["Controlled follow-up", "WorkItems keep the next action owned, timed and subject to the right approval boundary."]],
    controlLabel: "Human control", controlTitle: "Sales speed without hidden authority.",
    controls: [["Approvals", "Review consequential outbound actions."], ["Handoff", "Move a conversation to a person."], ["Permissions", "Limit tools and actions by role."], ["Audit", "Understand what happened and why."]],
    viewLabel: "Sales operating view", viewTitle: "One context from conversation to outcome.",
    viewCopy: "Inbox captures conversation, WorkItems structure execution, approvals govern sensitive actions, and analytics summarize persisted activity—without invented dashboard metrics.",
    operating: [["Inbox", "Intent and conversations"], ["WorkItems", "Ownership and progress"], ["Approvals", "Human decisions"], ["Analytics", "Recorded activity and outcomes"]]
  },
  about: {
    eyebrow: "About", title: "Make AI work useful, controllable and accountable.",
    lead: "Businesses will increasingly operate with both people and AI employees. HIRI exists to make that workforce connected to real systems and governed like real operations.",
    missionLabel: "Product mission", missionTitle: "Real work over AI demonstrations.",
    missionCopy: "HIRI brings roles, capabilities, tools, policies, approvals, cost visibility and audit history into one coherent product—so automation can create value without obscuring responsibility.",
    principles: [["Human governance", "People retain authority at meaningful decision points."], ["Reusable employees and capabilities", "Operating knowledge can serve more than one workflow."], ["Replaceable providers and integrations", "The operating model is not locked to one external vendor."], ["Controlled cost", "Usage is observable in the context of work."], ["One coherent platform", "Departments share the same control and execution language."]]
  },
  contact: {
    eyebrow: "Contact", title: "Choose the right way to begin with HIRI.",
    lead: "The current public experience does not expose a contact-submission endpoint. We will not pretend a message has been sent.",
    accessTitle: "Start with product access", accessCopy: "Create an account to establish your operator identity and continue into the HIRI workspace experience.",
    returnTitle: "Already operating HIRI?", returnCopy: "Sign in to return to your workspace and AI workforce.",
    directTitle: "Direct enquiries", directCopy: "A verified public contact channel will be published here when it is supported. No form on this page submits data today.",
    login: "Log in"
  }
};

const fr: typeof en = {
  common: { create: "Créer un compte", how: "Découvrir le fonctionnement", platform: "Explorer la plateforme", sales: "Découvrir HIRI Sales", controlled: "Exécution maîtrisée", result: "Résultat métier", approval: "Approbation si nécessaire", audit: "Audit et analyses", finalTitle: "Constituez votre workforce IA.", finalCopy: "Commencez avec un employé spécialisé. Développez votre organisation lorsque votre modèle opérationnel est prêt.", workItem: "WorkItem", employee: "Employé IA", tool: "Outil autorisé", event: "Événement métier" },
  home: {
    eyebrow: "Plateforme de workforce IA", title: "Constituez votre workforce IA.", lead: "Des employés IA qui réalisent un véritable travail métier avec les outils, données et canaux de votre entreprise, sous contrôle des permissions, approbations, coûts et audits.",
    visualTitle: "Exécution maîtrisée", request: "Demande commerciale entrante", assigned: "Qualification commerciale", permission: "Accès CRM autorisé", output: "Opportunité qualifiée enregistrée",
    whatLabel: "Ce qu’est HIRI", whatTitle: "Une plateforme. Des employés IA. Une exécution métier réelle.", whatCopy: "Développez la workforce par étapes, sans perdre la responsabilité, le contexte ni le contrôle.",
    levels: [["01", "Un employé IA", "Un rôle précis avec des instructions, capacités et accès approuvés."], ["02", "Une équipe IA spécialisée", "Plusieurs employés coordonnés autour d’un résultat métier commun."], ["03", "Un département IA", "Un travail récurrent supervisé dans une même fonction opérationnelle."], ["04", "Des départements coordonnés", "Un modèle partagé à l’échelle de l’entreprise lorsqu’elle est prête."]],
    flowLabel: "Circulation du travail", flowTitle: "De la demande au résultat traçable.", flowCopy: "Chaque unité d’exécution significative peut devenir un WorkItem : visible, attribué, gouverné et vérifiable.", flow: ["Événement métier", "WorkItem", "Employé IA compétent", "Capacité et outil autorisés", "Approbation si nécessaire", "Résultat métier", "Audit"],
    salesLabel: "Les ventes d’abord", salesTitle: "Un point de départ mature pour la workforce IA.", salesCopy: "HIRI Sales est conçu pour capter l’intention d’achat, comprendre le contexte et faire progresser le travail qualifié selon vos règles.", salesFlow: ["Capter", "Comprendre", "Qualifier", "Échanger", "Relancer", "Convertir"], channelsLabel: "Conçu pour se connecter à des canaux tels que", channels: ["Site web", "Facebook", "Instagram", "WhatsApp", "E-mail", "Formulaires", "API et webhooks"],
    controlLabel: "Contrôle humain", controlTitle: "L’autorité se mérite, elle ne se présume pas.", controlCopy: "HIRI n’accorde à chaque employé que les capacités, outils et niveaux d’autonomie nécessaires à son rôle. Le travail sensible peut s’arrêter à une décision humaine.", controls: [["Permissions", "Définissent ce que l’employé peut faire."], ["Politiques", "Appliquent les règles métier avant l’action."], ["Approbations", "Maintiennent l’humain aux décisions importantes."], ["Outils autorisés", "Limitent les surfaces d’exécution externes."], ["Historique d’audit", "Conserve une trace vérifiable."], ["Utilisation et coût", "Suit la consommation des modèles en contexte."]],
    platformLabel: "Aperçu de la plateforme", platformTitle: "La couche opérationnelle derrière chaque employé.", areas: [["Workforce IA", "Rôles et capacités"], ["WorkItems", "Unités de travail attribuées"], ["Approbations", "Décisions humaines"], ["Intégrations", "Accès gouverné aux outils"], ["AI Gateway", "Modèles, utilisation et coût"], ["Audit / Analyses", "Visibilité opérationnelle"]]
  },
  platform: {
    eyebrow: "Plateforme", title: "Le système d’exploitation d’une workforce IA.", lead: "HIRI coordonne employés, travail, permissions, outils et résultats dans une structure opérationnelle maîtrisée.",
    workforceLabel: "Workforce IA", workforceTitle: "Chaque employé possède une identité opérationnelle explicite.", workforceCopy: "Les départements définissent la responsabilité. Les superviseurs coordonnent le travail. Les spécialistes n’exécutent qu’avec les capacités et accès qui leur sont attribués.", employeeFields: [["Rôle", "La responsabilité de l’employé"], ["Instructions", "La manière de traiter le travail"], ["Capacités", "Les compétences métier disponibles"], ["Accès aux outils", "Les systèmes externes utilisables"], ["Permissions", "Les limites de l’autorité"], ["Connaissances", "Le contexte d’entreprise disponible"], ["Autonomie", "Le moment où une personne décide"], ["Indicateurs", "Le suivi de l’activité et des résultats"]],
    workLabel: "Exécution des WorkItems", workTitle: "Une unité universelle de travail visible.", workCopy: "Un WorkItem transporte responsabilité, état, entrées, approbations et résultats au fil d’un cycle vérifiable.", lifecycle: ["Créé", "Attribué", "En cours", "En attente ou approbation requise", "Terminé"], exceptions: "Les états échoué, annulé et expiré rendent les exceptions explicites.",
    govLabel: "Gouvernance", govTitle: "L’autonomie dans un périmètre défini.", autonomy: [["1", "Suggérer", "HIRI recommande ; une personne agit."], ["2", "Préparer + approbation", "HIRI prépare ; une personne autorise."], ["3", "Automatisation maîtrisée", "HIRI agit avec des permissions explicites."], ["4", "Automatisation élevée", "HIRI opère dans un périmètre approuvé et restreint."]], guardrails: ["Permissions", "Politiques", "Outils autorisés", "Approbations", "Historique d’audit"],
    connectLabel: "Connectivité", connectTitle: "Les outils externes exécutent les actions autorisées.", connectCopy: "HIRI est conçu pour se connecter aux canaux et systèmes métier tout en conservant les décisions et l’état des WorkItems dans HIRI. La disponibilité dépend de l’intégration configurée.", connections: ["Meta", "WhatsApp", "Gmail", "Outlook", "Google Calendar", "CRM", "Shopify", "WooCommerce", "Slack", "API", "Webhooks", "MCP", "n8n"],
    gatewayLabel: "AI Gateway", gatewayTitle: "Les modèles restent remplaçables. L’utilisation reste observable.", gatewayCopy: "Une passerelle partagée peut abstraire les fournisseurs, router les modèles, appliquer quotas et replis, et enregistrer utilisation, coûts et journaux opérationnels.", gatewayItems: ["Abstraction des fournisseurs", "Routage des modèles", "Suivi de l’utilisation et des coûts", "Quotas et replis", "Journalisation et observabilité"],
    contextLabel: "Contexte métier partagé", contextTitle: "Les départements travaillent à partir d’une même réalité métier.", contextCopy: "HIRI réutilise des objets métier communs au lieu de créer un système client isolé pour chaque département.", objects: ["Client", "Prospect", "Contact", "Conversation", "Produit", "Commande", "Facture", "Ticket", "WorkItem"]
  },
  how: {
    eyebrow: "Fonctionnement", title: "De l’événement métier à l’exécution gouvernée.", lead: "HIRI transforme le travail entrant en une chaîne maîtrisée de responsabilité, capacité, permission et résultat.", processLabel: "Modèle d’exécution", processTitle: "Douze contrôles, un parcours compréhensible.",
    steps: [["01", "Le travail entre dans HIRI", "Un message, un événement ou un besoin planifié crée une demande."], ["02", "L’espace est identifié", "Le travail reste dans le périmètre de la bonne entreprise."], ["03", "Le département en répond", "Une fonction métier devient responsable du résultat."], ["04", "Le superviseur oriente", "La coordination choisit le parcours opérationnel adapté."], ["05", "Le spécialiste est choisi", "Un employé IA éligible reçoit le travail."], ["06", "La capacité est résolue", "HIRI confirme la compétence métier requise."], ["07", "L’outil autorisé est vérifié", "Seules les surfaces approuvées sont envisagées."], ["08", "Les politiques s’appliquent", "Permissions et règles métier sont évaluées."], ["09", "Le WorkItem s’exécute", "Entrées, état et progression restent visibles."], ["10", "Approbation humaine", "Les actions importantes s’arrêtent si nécessaire."], ["11", "Le résultat est produit", "Le résultat métier est enregistré."], ["12", "L’historique est mis à jour", "Audit et analyses conservent la trace opérationnelle."]],
    differenceLabel: "Contrôlé par conception", differenceTitle: "Plus responsable qu’un agent sans limites.", unrestricted: "Agent sans limites", unrestrictedCopy: "Un accès large et des actions peu encadrées compliquent la responsabilité et la vérification.", hiriModel: "Exécution HIRI", formula: ["Rôle", "Capacité", "Outil autorisé", "Permission", "Politique", "Approbation", "Audit"], boundaryTitle: "Le contrôle humain là où il compte.", boundaryCopy: "Le travail courant avance dans le cadre des politiques. Les actions externes sensibles peuvent s’arrêter en présentant au réviseur le WorkItem, le demandeur, l’action proposée et ses conséquences."
  },
  sales: {
    eyebrow: "HIRI Sales", title: "Des employés commerciaux IA pour un travail de revenu gouverné.", lead: "Traitez intention d’achat, qualification, conversation et relance grâce à des employés spécialisés opérant selon vos règles métier.", flow: ["Capter", "Comprendre", "Qualifier", "Échanger", "Relancer", "Convertir"],
    captureLabel: "Capture des prospects", captureTitle: "Transformez les signaux d’intention en travail structuré.", captureCopy: "HIRI Sales est conçu pour se connecter aux réseaux sociaux, sites, formulaires, e-mails, publicités et API. La disponibilité dépend de la configuration.", sources: ["Facebook", "Instagram", "WhatsApp", "Site web", "Formulaires", "E-mail", "Publicités et landing pages", "API et webhooks"], intentFlow: ["Le prospect manifeste une intention", "Le prospect est créé ou rapproché", "Le contexte est compris", "La qualification commence"],
    stages: [["Qualification", "Appliquez vos critères métier à l’intention, l’adéquation, le besoin et le contexte sans inventer de scores non pris en charge."], ["Conversation commerciale", "Les employés spécialisés répondent avec le contexte utile, avec reprise humaine si nécessaire."], ["Relance maîtrisée", "Les WorkItems maintiennent la prochaine action attribuée, planifiée et soumise au bon niveau d’approbation."]],
    controlLabel: "Contrôle humain", controlTitle: "La vitesse commerciale sans autorité cachée.", controls: [["Approbations", "Examinez les actions sortantes importantes."], ["Transfert", "Confiez une conversation à une personne."], ["Permissions", "Limitez outils et actions selon le rôle."], ["Audit", "Comprenez ce qui s’est passé et pourquoi."]],
    viewLabel: "Vue opérationnelle des ventes", viewTitle: "Un contexte unique, de la conversation au résultat.", viewCopy: "La boîte de réception capte les échanges, les WorkItems structurent l’exécution, les approbations gouvernent les actions sensibles et les analyses résument l’activité enregistrée, sans indicateurs inventés.", operating: [["Boîte de réception", "Intentions et conversations"], ["WorkItems", "Responsabilité et progression"], ["Approbations", "Décisions humaines"], ["Analyses", "Activité et résultats enregistrés"]]
  },
  about: { eyebrow: "À propos", title: "Rendre le travail IA utile, maîtrisable et responsable.", lead: "Les entreprises fonctionneront de plus en plus avec des personnes et des employés IA. HIRI vise à connecter cette workforce aux systèmes réels et à la gouverner comme de vraies opérations.", missionLabel: "Mission produit", missionTitle: "Le travail réel plutôt que les démonstrations IA.", missionCopy: "HIRI réunit rôles, capacités, outils, politiques, approbations, visibilité des coûts et audit dans un produit cohérent, afin que l’automatisation crée de la valeur sans masquer la responsabilité.", principles: [["Gouvernance humaine", "Les personnes gardent l’autorité aux décisions importantes."], ["Employés et capacités réutilisables", "Le savoir opérationnel peut servir plusieurs workflows."], ["Fournisseurs et intégrations remplaçables", "Le modèle opérationnel ne dépend pas d’un seul prestataire."], ["Coûts maîtrisés", "L’utilisation reste observable dans le contexte du travail."], ["Une plateforme cohérente", "Les départements partagent le même langage de contrôle et d’exécution."]] },
  contact: { eyebrow: "Contact", title: "Choisissez la bonne manière de commencer avec HIRI.", lead: "L’expérience publique actuelle ne propose aucun endpoint d’envoi de contact. Nous ne prétendrons pas qu’un message a été envoyé.", accessTitle: "Commencer par l’accès produit", accessCopy: "Créez un compte pour établir votre identité d’opérateur et poursuivre dans l’espace de travail HIRI.", returnTitle: "Vous utilisez déjà HIRI ?", returnCopy: "Connectez-vous pour retrouver votre espace et votre workforce IA.", directTitle: "Demandes directes", directCopy: "Un canal de contact public vérifié sera publié ici lorsqu’il sera pris en charge. Aucun formulaire de cette page n’envoie de données aujourd’hui.", login: "Se connecter" }
};

const ar: typeof en = {
  common: { create: "إنشاء حساب", how: "اكتشف آلية العمل", platform: "استكشف المنصة", sales: "استكشف HIRI Sales", controlled: "تنفيذ منضبط", result: "نتيجة العمل", approval: "موافقة عند الحاجة", audit: "التدقيق والتحليلات", finalTitle: "ابنِ قواك العاملة بالذكاء الاصطناعي.", finalCopy: "ابدأ بموظف متخصص واحد، ثم توسع عندما يصبح نموذجك التشغيلي جاهزًا.", workItem: "WorkItem", employee: "موظف ذكاء اصطناعي", tool: "أداة مسموح بها", event: "حدث في العمل" },
  home: {
    eyebrow: "منصة القوى العاملة بالذكاء الاصطناعي", title: "وظّف قواك العاملة بالذكاء الاصطناعي.", lead: "موظفون بالذكاء الاصطناعي ينجزون أعمالًا حقيقية باستخدام أدوات الشركة وبياناتها وقنواتها، ضمن صلاحيات وموافقات وضوابط تكلفة وسجل قابل للتدقيق.",
    visualTitle: "تنفيذ منضبط", request: "طلب مبيعات وارد", assigned: "تأهيل المبيعات", permission: "الوصول إلى CRM مسموح", output: "تم تسجيل فرصة مؤهلة",
    whatLabel: "ما هي HIRI", whatTitle: "منصة واحدة. موظفون بالذكاء الاصطناعي. تنفيذ حقيقي للأعمال.", whatCopy: "طوّر القوى العاملة على مراحل مدروسة من دون فقدان المسؤولية أو السياق أو التحكم.", levels: [["01", "موظف ذكاء اصطناعي واحد", "دور محدد بتعليمات وقدرات ووصول معتمد."], ["02", "فريق ذكاء اصطناعي متخصص", "عدة موظفين منسقين لتحقيق نتيجة عمل مشتركة."], ["03", "قسم بالذكاء الاصطناعي", "أعمال متكررة خاضعة للإشراف ضمن وظيفة تشغيلية واحدة."], ["04", "أقسام منسقة", "نموذج تشغيلي مشترك على مستوى الشركة عند نضجه."]],
    flowLabel: "مسار العمل", flowTitle: "من الطلب إلى نتيجة قابلة للمساءلة.", flowCopy: "يمكن أن تصبح كل وحدة تنفيذ مهمة WorkItem مرئية ومسندة ومحكومة وقابلة للمراجعة.", flow: ["حدث في العمل", "WorkItem", "موظف الذكاء الاصطناعي المناسب", "قدرة وأداة مسموح بهما", "موافقة عند الحاجة", "نتيجة العمل", "التدقيق"],
    salesLabel: "المبيعات أولًا", salesTitle: "نقطة بداية ناضجة للقوى العاملة بالذكاء الاصطناعي.", salesCopy: "صُممت HIRI Sales لالتقاط نية الشراء وفهم السياق ومواصلة العمل المؤهل وفق قواعد الشركة.", salesFlow: ["الالتقاط", "الفهم", "التأهيل", "المحادثة", "المتابعة", "التحويل"], channelsLabel: "مصممة للاتصال بقنوات مثل", channels: ["الموقع الإلكتروني", "Facebook", "Instagram", "WhatsApp", "البريد الإلكتروني", "النماذج", "واجهات API وخطافات الويب"],
    controlLabel: "التحكم البشري", controlTitle: "تُمنح الصلاحية بقدر الحاجة ولا تُفترض.", controlCopy: "تمنح HIRI كل موظف القدرات والأدوات والاستقلالية التي يتطلبها دوره فقط، ويمكن إيقاف العمل الحساس عند حد قرار بشري.", controls: [["الصلاحيات", "تحدد ما يستطيع الموظف فعله."], ["السياسات", "تطبق قواعد الشركة قبل التنفيذ."], ["الموافقات", "تبقي الإنسان عند القرارات المؤثرة."], ["الأدوات المسموح بها", "تحصر قنوات التنفيذ الخارجية."], ["سجل التدقيق", "يحفظ سجلًا قابلًا للمراجعة."], ["الاستخدام والتكلفة", "يرصد استهلاك النماذج ضمن سياقه."]],
    platformLabel: "لمحة عن المنصة", platformTitle: "الطبقة التشغيلية خلف كل موظف.", areas: [["القوى العاملة الذكية", "الأدوار والقدرات"], ["WorkItems", "وحدات العمل المسندة"], ["الموافقات", "نقاط القرار البشري"], ["التكاملات", "وصول محكوم إلى الأدوات"], ["AI Gateway", "النماذج والاستخدام والتكلفة"], ["التدقيق والتحليلات", "الرؤية التشغيلية"]]
  },
  platform: {
    eyebrow: "المنصة", title: "نظام تشغيل للقوى العاملة بالذكاء الاصطناعي.", lead: "تنسق HIRI الموظفين والعمل والصلاحيات والأدوات والنتائج ضمن هيكل تشغيلي واحد ومنضبط.", workforceLabel: "القوى العاملة الذكية", workforceTitle: "لكل موظف هوية تشغيلية واضحة.", workforceCopy: "تحدد الأقسام المسؤولية، وينسق المشرفون العمل، ولا ينفذ الموظفون المتخصصون إلا عبر القدرات والوصول المسند إليهم.", employeeFields: [["الدور", "ما يتحمل الموظف مسؤوليته"], ["التعليمات", "كيفية معالجة العمل"], ["القدرات", "مهارات العمل المتاحة"], ["الوصول إلى الأدوات", "الأنظمة الخارجية القابلة للاستخدام"], ["الصلاحيات", "حدود السلطة الممنوحة"], ["المعرفة", "سياق الشركة المتاح"], ["الاستقلالية", "متى يجب أن يقرر الإنسان"], ["المؤشرات", "كيفية رصد النشاط والنتائج"]],
    workLabel: "تنفيذ WorkItem", workTitle: "وحدة عالمية واحدة للعمل المرئي.", workCopy: "يحمل WorkItem المسؤولية والحالة والمدخلات والموافقات والنتائج عبر دورة حياة قابلة للمراجعة.", lifecycle: ["تم الإنشاء", "تم الإسناد", "قيد التنفيذ", "انتظار أو موافقة مطلوبة", "مكتمل"], exceptions: "تُظهر حالات الفشل والإلغاء وانتهاء الصلاحية الاستثناءات بوضوح.",
    govLabel: "الحوكمة", govTitle: "استقلالية ضمن حدود محددة.", autonomy: [["1", "الاقتراح", "توصي HIRI ويتولى الإنسان التنفيذ."], ["2", "الإعداد والموافقة البشرية", "تُعد HIRI ويمنح الإنسان الإذن."], ["3", "الأتمتة المنضبطة", "تعمل HIRI بصلاحيات صريحة."], ["4", "الأتمتة العالية", "تعمل HIRI ضمن نطاق ضيق ومعتمد."]], guardrails: ["الصلاحيات", "السياسات", "الأدوات المسموح بها", "الموافقات", "سجل التدقيق"],
    connectLabel: "الاتصال", connectTitle: "تنفذ الأدوات الخارجية الإجراءات المسموح بها.", connectCopy: "صُممت HIRI للاتصال بقنوات وأنظمة الأعمال مع إبقاء القرارات وحالة WorkItems داخل HIRI. يعتمد التوفر على التكامل المهيأ.", connections: ["Meta", "WhatsApp", "Gmail", "Outlook", "Google Calendar", "CRM", "Shopify", "WooCommerce", "Slack", "API", "Webhooks", "MCP", "n8n"],
    gatewayLabel: "AI Gateway", gatewayTitle: "تبقى النماذج قابلة للاستبدال ويبقى الاستخدام قابلًا للرصد.", gatewayCopy: "يمكن لبوابة مشتركة تجريد المزوّدين وتوجيه النماذج وتطبيق الحصص والبدائل وتسجيل الاستخدام والتكلفة والسجلات التشغيلية.", gatewayItems: ["تجريد المزوّدين", "توجيه النماذج", "تتبع الاستخدام والتكلفة", "الحصص والبدائل", "التسجيل وقابلية الرصد"], contextLabel: "سياق عمل مشترك", contextTitle: "تعمل الأقسام انطلاقًا من واقع عمل واحد.", contextCopy: "تعيد HIRI استخدام عناصر العمل المشتركة بدل إنشاء نظام عملاء منفصل لكل قسم.", objects: ["العميل", "العميل المحتمل", "جهة الاتصال", "المحادثة", "المنتج", "الطلب", "الفاتورة", "التذكرة", "WorkItem"]
  },
  how: {
    eyebrow: "آلية العمل", title: "من حدث في العمل إلى تنفيذ محكوم.", lead: "تحوّل HIRI العمل الوارد إلى سلسلة منضبطة من المسؤولية والقدرة والصلاحية والنتيجة.", processLabel: "نموذج التنفيذ", processTitle: "اثنتا عشرة نقطة تحقق ضمن مسار واضح.", steps: [["01", "يدخل العمل إلى HIRI", "تنشئ رسالة أو واقعة أو حاجة مجدولة طلبًا للعمل."], ["02", "تُحدد مساحة العمل", "يبقى العمل داخل حدود الشركة الصحيحة."], ["03", "يتولى القسم المسؤولية", "تصبح وظيفة عمل محددة مسؤولة عن النتيجة."], ["04", "يوجه المشرف العمل", "يختار التنسيق المسار التشغيلي المناسب."], ["05", "يُختار المتخصص", "يتلقى موظف ذكاء اصطناعي مؤهل العمل."], ["06", "تُحدد القدرة", "تتحقق HIRI من مهارة العمل المطلوبة."], ["07", "تُفحص الأداة المسموح بها", "لا تُعتمد إلا وسائل التنفيذ الموافق عليها."], ["08", "تُطبق السياسات", "تُقيّم الصلاحيات وقواعد الشركة."], ["09", "يُنفذ WorkItem", "تبقى المدخلات والحالة والتقدم مرئية."], ["10", "الموافقة البشرية", "تتوقف الإجراءات المؤثرة عند الحاجة."], ["11", "تُنتج النتيجة", "تُسجل نتيجة العمل."], ["12", "يُحدّث السجل", "يحفظ التدقيق والتحليلات السجل التشغيلي."]],
    differenceLabel: "محكوم منذ التصميم", differenceTitle: "مساءلة أوضح من وكيل غير مقيد.", unrestricted: "وكيل غير مقيد", unrestrictedCopy: "يصعّب الوصول الواسع والتصرف غير المحدود تحديد المسؤولية والمراجعة.", hiriModel: "تنفيذ HIRI", formula: ["الدور", "القدرة", "الأداة المسموح بها", "الصلاحية", "السياسة", "الموافقة", "التدقيق"], boundaryTitle: "تحكم بشري حيث تهم القرارات.", boundaryCopy: "يمكن للعمل الروتيني التقدم ضمن السياسة، بينما تتوقف الإجراءات الخارجية الحساسة مع عرض WorkItem وصاحب الطلب والإجراء المقترح والنتيجة على المراجع."
  },
  sales: {
    eyebrow: "HIRI Sales", title: "موظفو مبيعات بالذكاء الاصطناعي لأعمال إيرادات محكومة.", lead: "عالج نية الشراء الواردة والتأهيل والمحادثة والمتابعة عبر موظفين متخصصين يعملون وفق قواعد شركتك.", flow: ["الالتقاط", "الفهم", "التأهيل", "المحادثة", "المتابعة", "التحويل"], captureLabel: "التقاط العملاء المحتملين", captureTitle: "حوّل إشارات الاهتمام إلى عمل منظم.", captureCopy: "صُممت HIRI Sales للاتصال بمصادر واردة مثل الشبكات الاجتماعية والمواقع والنماذج والبريد والإعلانات وواجهات API. يعتمد التوفر على التهيئة.", sources: ["Facebook", "Instagram", "WhatsApp", "الموقع الإلكتروني", "النماذج", "البريد الإلكتروني", "الإعلانات وصفحات الهبوط", "واجهات API وخطافات الويب"], intentFlow: ["يُظهر العميل المحتمل اهتمامًا", "يُنشأ العميل أو تُطابق بياناته", "يُفهم السياق", "يبدأ التأهيل"],
    stages: [["التأهيل", "طبّق معايير الشركة على النية والملاءمة والحاجة والسياق من دون ادعاء درجات غير مدعومة."], ["محادثة المبيعات", "يرد الموظفون المتخصصون بالسياق المناسب مع إمكانية تسليم المحادثة إلى إنسان."], ["متابعة منضبطة", "تحافظ WorkItems على إسناد الإجراء التالي وتوقيته وخضوعه للموافقة المناسبة."]], controlLabel: "التحكم البشري", controlTitle: "سرعة في المبيعات من دون صلاحيات خفية.", controls: [["الموافقات", "راجع الإجراءات الخارجية المؤثرة."], ["التسليم", "انقل المحادثة إلى موظف بشري."], ["الصلاحيات", "قيّد الأدوات والإجراءات حسب الدور."], ["التدقيق", "افهم ما حدث وسببه."]], viewLabel: "منظور تشغيل المبيعات", viewTitle: "سياق واحد من المحادثة إلى النتيجة.", viewCopy: "يلتقط صندوق الوارد المحادثات، وتنظم WorkItems التنفيذ، وتحكم الموافقات الإجراءات الحساسة، وتلخص التحليلات النشاط المحفوظ من دون مؤشرات مختلقة.", operating: [["صندوق الوارد", "الاهتمام والمحادثات"], ["WorkItems", "المسؤولية والتقدم"], ["الموافقات", "القرارات البشرية"], ["التحليلات", "النشاط والنتائج المسجلة"]]
  },
  about: { eyebrow: "حول HIRI", title: "اجعل عمل الذكاء الاصطناعي مفيدًا ومنضبطًا وخاضعًا للمساءلة.", lead: "ستعمل الشركات بصورة متزايدة بقوى تجمع بين البشر وموظفي الذكاء الاصطناعي. وتهدف HIRI إلى ربط هذه القوى بالأنظمة الحقيقية وحوكمتها كعمليات فعلية.", missionLabel: "مهمة المنتج", missionTitle: "العمل الحقيقي قبل عروض الذكاء الاصطناعي.", missionCopy: "تجمع HIRI الأدوار والقدرات والأدوات والسياسات والموافقات ورؤية التكلفة وسجل التدقيق في منتج واحد، كي تصنع الأتمتة قيمة من دون إخفاء المسؤولية.", principles: [["الحوكمة البشرية", "يحتفظ البشر بالسلطة عند القرارات المهمة."], ["موظفون وقدرات قابلة لإعادة الاستخدام", "يمكن للمعرفة التشغيلية خدمة أكثر من سير عمل."], ["مزوّدون وتكاملات قابلة للاستبدال", "لا يرتبط النموذج التشغيلي بمزوّد خارجي واحد."], ["تكلفة منضبطة", "يبقى الاستخدام مرئيًا في سياق العمل."], ["منصة واحدة متماسكة", "تتشارك الأقسام لغة التحكم والتنفيذ نفسها."]] },
  contact: { eyebrow: "تواصل معنا", title: "اختر الطريقة المناسبة للبدء مع HIRI.", lead: "لا توفر التجربة العامة الحالية نقطة إرسال لطلبات التواصل، ولن ندّعي أن رسالة قد أُرسلت.", accessTitle: "ابدأ بالوصول إلى المنتج", accessCopy: "أنشئ حسابًا لتأسيس هوية المشغّل ومتابعة الدخول إلى تجربة مساحة عمل HIRI.", returnTitle: "تستخدم HIRI بالفعل؟", returnCopy: "سجّل الدخول للعودة إلى مساحة عملك وقواك العاملة بالذكاء الاصطناعي.", directTitle: "الاستفسارات المباشرة", directCopy: "ستُنشر هنا قناة تواصل عامة موثقة عند دعمها. لا يرسل أي نموذج في هذه الصفحة بيانات حاليًا.", login: "تسجيل الدخول" }
};

export function usePublicContent() {
  const { locale } = useAppExperience();
  return ({ en, fr, ar } as const)[locale];
}
