import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckSquare, X } from "lucide-react";
import { useEffect, useState } from "react";

import { useAuth } from "../auth/AuthProvider";
import { ApprovalStatusBadge, DefinitionList, formatDate, label } from "../components/operator/OperatorDisplay";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { EmptyState } from "../components/ui/EmptyState";
import { ErrorState } from "../components/ui/ErrorState";
import { LoadingState } from "../components/ui/LoadingState";
import { PageHeader } from "../components/ui/PageHeader";
import { apiClient } from "../lib/api";
import { queryKeys } from "../lib/queryKeys";
import type { OperatorApprovalRead } from "../types/api";
import { useWorkspace } from "../workspaces/WorkspaceProvider";

export function ApprovalsPage() {
  const { token } = useAuth(); const { selectedWorkspace, selectedWorkspaceSlug } = useWorkspace(); const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null); const [note, setNote] = useState(""); const [feedback, setFeedback] = useState<string | null>(null);
  useEffect(() => { setSelectedId(null); setFeedback(null); }, [selectedWorkspaceSlug]);
  const query = useQuery({ queryKey: queryKeys.operatorApprovals(selectedWorkspaceSlug ?? "none"), queryFn: () => apiClient.operatorApprovals(token as string, selectedWorkspaceSlug as string), enabled: Boolean(token && selectedWorkspaceSlug) });
  const selected = query.data?.find((approval) => approval.id === selectedId) ?? null;
  const mutation = useMutation({ mutationFn: ({ id, decision }: { id: string; decision: "approve" | "reject" }) => apiClient.decideApproval(token as string, selectedWorkspaceSlug as string, id, decision, note), onSuccess: async (_, variables) => { setFeedback(variables.decision === "approve" ? "Approval recorded. Authorized work may still require backend execution." : "Rejection recorded."); setNote(""); await Promise.all([queryClient.invalidateQueries({ queryKey: queryKeys.operatorApprovals(selectedWorkspaceSlug as string) }), queryClient.invalidateQueries({ queryKey: ["operator", selectedWorkspaceSlug, "work-items"] })]); }, onError: () => setFeedback(null) });
  return <div><PageHeader eyebrow="Human review" title="Approvals" description="Review proposed business actions and use the existing approval decision boundary." action={<Badge tone="amber">{query.data?.filter((item) => item.status === "pending").length ?? 0} pending</Badge>} /><div className="space-y-5 p-5 sm:p-7">{feedback ? <div role="status" className="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{feedback}</div> : null}{query.isLoading ? <LoadingState label="Loading approvals" /> : null}{query.error ? <ErrorState description="Unable to load approvals for this workspace." /> : null}{!query.isLoading && !query.error && !query.data?.length ? <EmptyState icon={CheckSquare} title="No approvals waiting for review." description="Approval requests will appear here when HIRI work needs a human decision." /> : null}<div className="grid gap-4 lg:grid-cols-2">{query.data?.map((approval) => <Card key={approval.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{approval.work_item_title || label(approval.action_type)}</h2><p className="mt-1 text-sm text-slate-500">{approval.work_type ? label(approval.work_type) : label(approval.action_type)} · {formatDate(approval.created_at)}</p></div><ApprovalStatusBadge status={approval.status} /></div><p className="mt-4 text-sm text-slate-700">{approval.lead_name ? `${approval.lead_name}${approval.company_name ? ` · ${approval.company_name}` : ""}` : approval.ai_employee_name || "Workspace business action"}</p><Button className="mt-4" variant="secondary" onClick={() => { setSelectedId(approval.id); setFeedback(null); }}>Review details</Button></Card>)}</div></div>{selected ? <ApprovalDetail approval={selected} note={note} setNote={setNote} pending={mutation.isPending} error={mutation.error} onDecision={(decision) => mutation.mutate({ id: selected.id, decision })} onClose={() => setSelectedId(null)} /> : null}</div>;
}

function ApprovalDetail({ approval, note, setNote, pending, error, onDecision, onClose }: { approval: OperatorApprovalRead; note: string; setNote: (value: string) => void; pending: boolean; error: Error | null; onDecision: (decision: "approve" | "reject") => void; onClose: () => void }) { return <div className="fixed inset-0 z-40 flex justify-end bg-slate-950/40" role="dialog" aria-modal="true" aria-label="Approval details"><button className="absolute inset-0" aria-label="Close approval details" onClick={onClose} /><aside className="relative h-full w-full max-w-xl overflow-y-auto bg-white p-5 shadow-2xl sm:p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Approval detail</p><h2 className="mt-1 text-xl font-semibold">{approval.work_item_title || label(approval.action_type)}</h2><div className="mt-3"><ApprovalStatusBadge status={approval.status} /></div></div><Button variant="ghost" className="px-3" aria-label="Close details" onClick={onClose}><X className="h-5 w-5" /></Button></div><div className="mt-6 space-y-6"><DefinitionList values={{ requested_action: approval.action_type, channel: approval.channel, lead: approval.lead_name, company: approval.company_name, work_type: approval.work_type, work_item_status: approval.work_item_status, ai_employee: approval.ai_employee_name, capability: approval.capability_key, integration: approval.integration_external_account_id || approval.integration_provider, requested_at: formatDate(approval.created_at) }} /><section><h3 className="mb-3 font-semibold">Proposed action</h3><DefinitionList values={approval.payload} /></section>{approval.status === "pending" ? <section className="border-t border-slate-200 pt-5"><label className="text-sm font-medium text-slate-700">Reviewer note<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} className="mt-2 w-full rounded-md border border-slate-200 p-3" /></label>{error ? <p role="alert" className="mt-3 text-sm text-red-700">Unable to record this approval decision.</p> : null}<div className="mt-4 flex flex-wrap gap-3"><Button disabled={pending} onClick={() => onDecision("approve")}>{pending ? "Saving…" : "Approve"}</Button><Button disabled={pending} variant="secondary" className="border-red-200 text-red-700" onClick={() => onDecision("reject")}>Reject</Button></div><p className="mt-3 text-xs text-slate-500">Approval authorizes the action; it does not guarantee execution or delivery.</p></section> : approval.reviewer_note ? <DefinitionList values={{ reviewer_note: approval.reviewer_note, decided_at: formatDate(approval.decided_at) }} /> : null}</div></aside></div>; }
