import {
  ArrowRight, BarChart3, Bot, BriefcaseBusiness, Building2, CalendarDays, Check,
  CheckCircle2, ChevronRight, CircleDollarSign, Clock3, CreditCard, Database,
  FileCheck2, Globe2, Mail, Menu, MessageCircle, MessagesSquare, Network, PlugZap,
  Send, ShieldCheck, ShoppingBag, Target, UserCheck, UsersRound, Workflow, X, Zap
} from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

const navigation = [
  ["Product", "#product"], ["Sales", "#sales"], ["How it works", "#how-it-works"],
  ["Platform", "#platform"], ["About", "#about"]
];

const workforceLevels = [
  ["01", "One AI employee", "Give a focused role clear instructions, approved tools and the right level of autonomy.", Bot],
  ["02", "A specialized AI team", "Coordinate specialists around a shared outcome while keeping responsibilities visible.", UsersRound],
  ["03", "A complete AI department", "Operate repeatable business workflows through structured work, supervision and controls.", Building2]
] as const;

const employeeAttributes = ["Department and role", "Instructions and knowledge", "Business capabilities", "Allowed tools", "Permissions and policies", "Autonomy level", "Model preferences", "Performance and usage"];
const salesStages = ["Capture", "Understand", "Qualify", "Converse", "Follow up", "Convert"];
const salesCapabilities = [
  ["Lead capture", "Turn inbound interest into structured, traceable Sales work.", Target],
  ["Qualification", "Move the right opportunities forward with a consistent view of fit.", CheckCircle2],
  ["Sales conversation", "Respond with context while sensitive actions stay governed.", MessageCircle],
  ["Follow-up", "Keep the next action visible and execute approved outreach.", Send]
] as const;
const workflowSteps = [
  ["Business event", "A message, lead or scheduled task creates demand for work."],
  ["Structured WorkItem", "The work becomes visible, owned and traceable from the start."],
  ["Eligible employee", "HIRI selects a specialist with the right role and capability."],
  ["Governed execution", "Permissions and autonomy determine which tools may be used."],
  ["Recorded result", "The outcome, activity, approval and cost remain reviewable."]
];
const platformAreas = [
  ["AI Workforce", "Employees, roles, departments and autonomy", UsersRound],
  ["Work Management", "WorkItems, assignments and outcomes", BriefcaseBusiness],
  ["Human Control", "Approvals, permissions and policies", ShieldCheck],
  ["Integrations", "Channels, tools and external execution", PlugZap],
  ["AI Gateway", "Models, usage policy and cost visibility", Network],
  ["Analytics", "Activity, outcomes and operating insight", BarChart3]
] as const;
const autonomyLevels = [
  ["01", "Suggest", "HIRI recommends what should happen; a person takes action."],
  ["02", "Draft + approve", "HIRI prepares the action and waits for human approval."],
  ["03", "Controlled automation", "HIRI acts within explicit tool permissions and policy."],
  ["04", "High automation", "HIRI operates independently inside a defined boundary."]
];
const currentIntegrations = ["WhatsApp", "Facebook", "Instagram", "Website / API", "Webhooks"];
const integrationDirection = [
  ["Gmail", Mail], ["Outlook", Mail], ["Calendar", CalendarDays], ["Sheets", Database],
  ["CRMs", BriefcaseBusiness], ["Commerce", ShoppingBag], ["Slack", MessagesSquare],
  ["Payments", CreditCard], ["APIs, MCP & n8n", Workflow]
] as const;
const benefits = [
  ["Respond faster", "Give prospects useful answers without waiting for every manual response.", Zap],
  ["Never lose track of work", "Make AI work visible, assigned and traceable through WorkItems.", BriefcaseBusiness],
  ["Keep follow-up consistent", "Give Sales a structured, durable view of the next action.", Clock3],
  ["Keep humans in control", "Govern sensitive actions through approvals and permissions.", ShieldCheck],
  ["Understand AI cost", "See model usage and cost in the context of real business work.", CircleDollarSign],
  ["Audit what happened", "Review important actions, decisions and results after the fact.", FileCheck2]
] as const;
const previewWorkItems = [
  ["Qualify inbound opportunity", "Lead Qualification", "In progress", "blue"],
  ["Prepare pricing response", "Sales Conversation", "Approval required", "amber"],
  ["Research new company", "Lead Research", "Queued", "slate"],
  ["Follow up after proposal", "Follow-up", "Completed", "green"]
];

function Brand({ inverted = false }: { inverted?: boolean }) {
  return <span className="inline-flex items-center gap-3"><img className="h-8 w-8" src="/hiri-logo.svg" alt="HIRI logo" /><span className={`text-[1.05rem] font-bold tracking-[0.22em] ${inverted ? "text-white" : "text-slate-950"}`}>HIRI</span></span>;
}

function SectionIntro({ label, title, copy, light = false }: { label: string; title: string; copy: string; light?: boolean }) {
  return <div className="max-w-3xl"><div className="flex items-center gap-3"><span className="h-px w-8 bg-brand-500" /><p className={`text-sm font-semibold ${light ? "text-blue-300" : "text-brand-600"}`}>{label}</p></div><h2 className={`mt-6 text-4xl font-semibold leading-[1.08] tracking-[-0.035em] sm:text-5xl ${light ? "text-white" : "text-slate-950"}`}>{title}</h2><p className={`mt-6 max-w-2xl text-lg leading-8 ${light ? "text-slate-300" : "text-slate-600"}`}>{copy}</p></div>;
}

function Status({ status, tone }: { status: string; tone: string }) {
  const color = { blue: "bg-blue-500", amber: "bg-amber-400", green: "bg-emerald-400", slate: "bg-slate-400" }[tone];
  return <span className="inline-flex items-center gap-2 whitespace-nowrap text-[10px] font-semibold text-slate-500"><span className={`h-1.5 w-1.5 rounded-full ${color}`} />{status}</span>;
}

function ProductSurface({ hero = false }: { hero?: boolean }) {
  return <div className={`hiri-product-frame relative overflow-hidden border border-white/10 bg-[#0b1424] ${hero ? "shadow-[0_38px_100px_rgba(0,0,0,0.45)]" : "shadow-[0_30px_90px_rgba(8,15,28,0.16)]"}`} aria-label="Illustrative HIRI Sales operations workspace">
    <div className="flex h-12 items-center justify-between border-b border-white/10 px-4 sm:px-5"><div className="flex items-center gap-3"><img className="h-6 w-6" src="/hiri-logo.svg" alt="" /><span className="text-xs font-semibold text-white">Sales Operations</span><span className="hidden text-[10px] text-slate-500 sm:inline">/ Overview</span></div><div className="flex items-center gap-2 text-[10px] text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_0_4px_rgba(52,211,153,0.1)]" />Operating</div></div>
    <div className="grid min-h-[400px] sm:grid-cols-[9rem_1fr]">
      <aside className="hidden border-r border-white/10 bg-[#080f1c] px-3 py-5 sm:block" aria-label="Illustrative product navigation"><p className="px-2 text-[9px] font-semibold uppercase tracking-[0.18em] text-slate-600">Workspace</p><div className="mt-3 space-y-1">{["Overview", "AI Workforce", "WorkItems", "Approvals", "Analytics"].map((item, i) => <div key={item} className={`flex items-center gap-2.5 rounded-md px-2 py-2 text-[10px] ${i === 0 ? "bg-blue-500/15 font-semibold text-blue-300" : "text-slate-500"}`}><span className={`h-1.5 w-1.5 rounded-sm ${i === 0 ? "bg-blue-400" : "bg-slate-700"}`} />{item}</div>)}</div><div className="mt-24 border-t border-white/10 pt-4"><p className="px-2 text-[9px] text-slate-600">Sales department</p><p className="mt-1 px-2 text-[10px] font-medium text-slate-400">4 AI employees</p></div></aside>
      <div className="min-w-0 bg-[#f6f8fb]"><div className="border-b border-slate-200 px-4 py-4 sm:px-5"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] text-slate-500">Sales department</p><p className="mt-1 text-sm font-semibold text-slate-950">Operating overview</p></div><p className="hidden text-[9px] text-slate-400 sm:block">Illustrative product surface</p></div><div className="mt-4 grid grid-cols-2 border-y border-slate-200 sm:grid-cols-4">{[["AI Employees", "4"], ["WorkItems", "18"], ["Approvals", "2"], ["AI Cost", "$8.42"]].map(([label, value], i) => <div key={label} className={`py-3 ${i % 2 ? "border-l border-slate-200 pl-3" : "pr-3"} sm:border-l sm:px-3 sm:first:border-l-0 sm:first:pl-0`}><p className="text-[9px] font-medium text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold tracking-tight text-slate-950">{value}</p></div>)}</div></div>
        <div className="grid lg:grid-cols-[1fr_10rem]"><div className="min-w-0 p-4 sm:p-5"><div className="mb-3 flex justify-between"><p className="text-[11px] font-semibold text-slate-800">Priority WorkItems</p><span className="text-[9px] font-semibold text-brand-600">View all</span></div><div className="divide-y divide-slate-200 border-y border-slate-200">{previewWorkItems.map(([title, owner, status, tone]) => <div key={title} className="grid grid-cols-[1fr_auto] items-center gap-3 py-3"><div className="min-w-0"><p className="truncate text-[10px] font-medium text-slate-800">{title}</p><p className="mt-0.5 truncate text-[9px] text-slate-400">{owner}</p></div><Status status={status} tone={tone} /></div>)}</div></div><div className="hidden border-l border-slate-200 p-4 lg:block"><p className="text-[10px] font-semibold text-slate-800">Activity</p><div className="mt-4 space-y-5">{["Lead captured", "Qualified", "Approval requested", "Follow-up sent"].map((item, i) => <div key={item} className="relative flex gap-2.5">{i < 3 && <span className="absolute left-[4px] top-3 h-7 w-px bg-slate-200" />}<span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full border-2 border-white bg-brand-500 shadow-[0_0_0_1px_#bfdbfe]" /><div><p className="text-[9px] font-medium text-slate-700">{item}</p><p className="text-[8px] text-slate-400">Sales operations</p></div></div>)}</div></div></div>
      </div>
    </div>
  </div>;
}

export function LandingPage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => { if (!mobileOpen) return; const close = (e: KeyboardEvent) => e.key === "Escape" && setMobileOpen(false); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [mobileOpen]);
  return <div className="marketing-page min-h-screen overflow-x-hidden bg-white text-slate-950">
    <a href="#main-content" className="sr-only z-[100] rounded-md bg-white px-4 py-2 font-semibold text-brand-700 focus:not-sr-only focus:fixed focus:left-4 focus:top-4">Skip to content</a>
    <div className="relative bg-[#07101f] text-white"><div className="hiri-hero-grid absolute inset-0 opacity-50" /><div className="hiri-mark-geometry absolute -right-40 top-12 h-[42rem] w-[42rem] opacity-30" />
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#07101f]/90 backdrop-blur-xl"><div className="mx-auto flex h-[4.5rem] max-w-[90rem] items-center justify-between px-5 sm:px-8 lg:px-12"><a href="#top" aria-label="HIRI homepage"><Brand inverted /></a><nav className="hidden items-center gap-8 lg:flex" aria-label="Public navigation">{navigation.map(([label, href]) => <a key={label} href={href} className="text-[13px] font-medium text-slate-400 transition hover:text-white">{label}</a>)}</nav><div className="hidden items-center gap-4 lg:flex"><Link to="/login" className="px-3 py-2 text-[13px] font-semibold text-slate-300 hover:text-white">Log in</Link><a href="#demo" className="inline-flex min-h-10 items-center gap-2 rounded-md bg-brand-500 px-4 py-2 text-[13px] font-semibold">Book a demo<ArrowRight className="h-3.5 w-3.5" /></a></div><button type="button" className="inline-grid h-10 w-10 place-items-center rounded-md border border-white/15 text-slate-200 lg:hidden" aria-label={mobileOpen ? "Close navigation" : "Open navigation"} aria-expanded={mobileOpen} aria-controls="mobile-navigation" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>
      {mobileOpen && <nav id="mobile-navigation" className="border-t border-white/10 bg-[#07101f] px-5 py-5 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto max-w-[90rem] space-y-1">{navigation.map(([label, href]) => <a key={label} href={href} onClick={() => setMobileOpen(false)} className="block rounded-md px-3 py-3 text-sm font-semibold text-slate-300 hover:bg-white/5">{label}</a>)}<div className="grid grid-cols-2 gap-3 border-t border-white/10 pt-4"><Link to="/login" className="inline-flex min-h-11 items-center justify-center rounded-md border border-white/15 text-sm font-semibold">Log in</Link><a href="#demo" onClick={() => setMobileOpen(false)} className="inline-flex min-h-11 items-center justify-center rounded-md bg-brand-500 text-sm font-semibold">Book a demo</a></div></div></nav>}</header>
      <main id="main-content"><section id="top" className="relative pb-20 pt-16 sm:pb-24 sm:pt-20 lg:pb-32 lg:pt-28"><div className="relative mx-auto grid max-w-[90rem] gap-14 px-5 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:gap-10 lg:px-12"><div className="relative z-10 max-w-2xl"><div className="flex items-center gap-3 text-sm font-medium text-blue-300"><span className="h-px w-8 bg-blue-400" />AI Workforce Platform</div><h1 className="mt-8 text-[3.5rem] font-semibold leading-[0.94] tracking-[-0.055em] text-white sm:text-[4.8rem] lg:text-[5.6rem]">Hire your<br className="hidden sm:block" /> AI workforce.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-300">Build AI employees, specialized teams and departments that perform real business work—with permissions, approvals, cost control and auditability.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#demo" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-md bg-brand-500 px-5 py-3 text-sm font-semibold shadow-[0_12px_40px_rgba(37,99,235,0.3)]">Book a demo<ArrowRight className="h-4 w-4" /></a><a href="#product" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-md border border-white/15 px-5 py-3 text-sm font-semibold">Explore the platform<ChevronRight className="h-4 w-4" /></a></div><div className="mt-12 grid max-w-xl grid-cols-3 border-t border-white/10 pt-5 text-[11px] font-medium text-slate-400">{["Permission-aware", "Human-governed", "Business-ready"].map(item => <span key={item} className="flex items-center gap-2"><Check className="h-3.5 w-3.5 shrink-0 text-blue-400" />{item}</span>)}</div></div><div className="relative lg:translate-x-10"><ProductSurface hero /></div></div></section></main>
      <div className="relative border-y border-white/10 bg-[#091425]"><div className="mx-auto grid max-w-[90rem] grid-cols-2 px-5 sm:px-8 md:grid-cols-5 lg:px-12">{[[Bot, "AI Employees"], [UserCheck, "Human Control"], [ShieldCheck, "Tool Permissions"], [CircleDollarSign, "Cost Visibility"], [FileCheck2, "Auditability"]].map(([Icon, label]) => { const I = Icon as typeof Bot; return <div key={label as string} className="flex items-center gap-3 px-2 py-5 text-xs font-medium text-slate-400 md:border-l md:border-white/10 md:px-5 md:last:border-r"><I className="h-4 w-4 text-blue-400" />{label as string}</div>; })}</div></div>
    </div>
    <main>
      <section id="product" className="section-anchor py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-[84rem] px-5 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[1fr_0.58fr] lg:items-end"><SectionIntro label="The product" title="One platform for your AI workforce." copy="Start with a focused employee. Coordinate a specialized team. Build an operating department when the work is ready to scale." /><div className="border-l border-slate-200 pl-6 lg:mb-1"><p className="text-lg font-semibold tracking-tight">A workforce, not a collection of prompts.</p><p className="mt-3 max-w-md text-sm leading-7 text-slate-600">Every employee has a defined role, approved capabilities and an explicit operating boundary.</p></div></div>
      <div className="relative mt-14 border-y border-slate-300"><div className="absolute left-0 top-0 h-0.5 w-1/3 bg-brand-500" /><div className="grid lg:grid-cols-3">{workforceLevels.map(([num, title, copy, Icon], i) => <article key={num} className={`relative py-8 lg:min-h-64 lg:px-8 lg:py-9 ${i > 0 ? "border-t border-slate-200 lg:border-l lg:border-t-0" : ""}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold text-brand-600">{num}</span><Icon className="h-5 w-5 text-slate-400" /></div><h3 className="mt-10 text-2xl font-semibold tracking-[-0.025em] text-slate-950">{title}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-slate-600">{copy}</p>{i < 2 && <div className="absolute -right-3 top-1/2 z-10 hidden h-6 w-6 -translate-y-1/2 place-items-center rounded-full border border-slate-300 bg-white lg:grid"><ChevronRight className="h-3.5 w-3.5 text-brand-600" /></div>}</article>)}</div><div className="grid grid-cols-3 border-t border-slate-200 py-3 text-[10px] font-semibold text-slate-400"><span>FOCUSED ROLE</span><span className="text-center">COORDINATED WORK</span><span className="text-right">OPERATING SCALE</span></div></div>
      <div className="mt-14 grid overflow-hidden border border-slate-300 bg-slate-950 lg:grid-cols-[0.72fr_1.28fr]"><div className="relative overflow-hidden p-8 text-white sm:p-10 lg:p-12"><div className="hiri-mark-geometry absolute -bottom-40 -left-40 h-96 w-96 opacity-20" /><p className="relative text-sm font-semibold text-blue-300">Employee operating profile</p><h3 className="relative mt-5 max-w-md text-3xl font-semibold leading-tight tracking-[-0.03em]">What makes an AI employee an operating entity.</h3><p className="relative mt-5 max-w-md text-sm leading-7 text-slate-400">Clear responsibility, bounded execution and measurable work—not vague automation.</p></div><div className="grid grid-cols-2 bg-white sm:grid-cols-4">{employeeAttributes.map((item, i) => <div key={item} className={`min-h-28 border-slate-200 p-5 sm:min-h-32 ${i % 2 ? "border-l" : ""} ${i > 1 ? "border-t" : ""} sm:border-l sm:first:border-l-0 sm:[&:nth-child(5)]:border-l-0 sm:[&:nth-child(n+5)]:border-t`}><div className="flex items-center gap-3"><span className="text-[10px] font-semibold text-brand-600">0{i + 1}</span><span className="h-px flex-1 bg-slate-200" /></div><p className="mt-6 text-sm font-semibold leading-5 text-slate-800">{item}</p></div>)}</div></div></div></section>

      <section id="sales" className="section-anchor relative overflow-hidden bg-[#08111f] py-24 text-white sm:py-32"><div className="hiri-sales-lines absolute inset-0 opacity-50" /><div className="relative mx-auto max-w-[84rem] px-5 sm:px-8 lg:px-12"><div className="grid gap-12 lg:grid-cols-[0.78fr_1.22fr] lg:items-end"><SectionIntro light label="First mature department" title="Start with Sales." copy="HIRI Sales turns inbound interest into governed work—from capture and understanding to qualification, conversation and consistent follow-up." /><div><div className="flex justify-between border-b border-white/10 pb-3 text-[10px] text-slate-500"><span>INBOUND</span><span>OPERATING FLOW</span><span>OUTCOME</span></div><div className="mt-6 grid grid-cols-3 gap-y-8 sm:grid-cols-6">{salesStages.map((stage, i) => <div key={stage} className="relative"><span className={`grid h-9 w-9 place-items-center rounded-full border text-[10px] font-semibold ${i === 0 || i === 5 ? "border-blue-400 bg-blue-500" : "border-white/15 bg-white/[0.04]"}`}>0{i + 1}</span><p className="mt-3 text-xs text-slate-300">{stage}</p>{i < 5 && <span className="absolute left-10 top-[1.1rem] hidden h-px w-[calc(100%-2.75rem)] bg-white/15 sm:block" />}</div>)}</div></div></div><div className="mt-16 grid border-y border-white/10 lg:grid-cols-2"><div className="grid grid-cols-2">{salesCapabilities.map(([title, copy, Icon], i) => <article key={title} className={`min-h-56 p-6 sm:p-8 ${i % 2 === 0 ? "border-r border-white/10" : ""} ${i < 2 ? "border-b border-white/10" : ""}`}><Icon className="h-5 w-5 text-blue-400" /><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{copy}</p></article>)}</div><div className="border-t border-white/10 bg-white/[0.025] p-7 sm:p-10 lg:border-l lg:border-t-0"><p className="text-xs font-semibold text-blue-300">Live Sales work</p><h3 className="mt-2 text-xl font-semibold">Operational, visible, governed.</h3><div className="mt-8 divide-y divide-white/10 border-y border-white/10">{previewWorkItems.map(([title, owner, status, tone]) => <div key={title} className="grid grid-cols-[1fr_auto] items-center gap-5 py-5"><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-slate-500">{owner}</p></div><Status status={status} tone={tone} /></div>)}</div><div className="mt-8 flex flex-wrap gap-5 text-xs text-slate-500"><span className="text-slate-300">Inbound</span>{["WhatsApp", "Facebook", "Instagram", "Website / API"].map(x => <span key={x}>{x}</span>)}</div></div></div></div></section>

      <section id="how-it-works" className="section-anchor relative overflow-hidden py-20 sm:py-24 lg:py-28"><div className="hiri-workflow-grid absolute inset-0 opacity-60" /><div className="relative mx-auto grid max-w-[84rem] gap-12 px-5 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:items-start lg:gap-20 lg:px-12"><div className="lg:sticky lg:top-28"><SectionIntro label="How HIRI works" title="From business event to accountable result." copy="HIRI transforms incoming business demand into structured, governed and accountable work." /><div className="mt-10 hidden items-center gap-3 text-xs font-semibold text-slate-500 lg:flex"><span className="grid h-8 w-8 place-items-center border border-brand-200 bg-brand-50 text-brand-600"><Workflow className="h-4 w-4" /></span>One connected operating flow</div></div><ol className="relative before:absolute before:bottom-10 before:left-5 before:top-10 before:w-px before:bg-slate-300">{workflowSteps.map(([title, copy], i) => <li key={title} className="relative grid gap-3 pb-8 pl-16 last:pb-0 sm:grid-cols-[0.72fr_1.28fr] sm:gap-8"><span className={`absolute left-0 top-0 z-10 grid h-10 w-10 place-items-center border text-[10px] font-semibold ${i === 0 || i === workflowSteps.length - 1 ? "border-brand-500 bg-brand-500 text-white shadow-[0_0_0_6px_rgba(37,99,235,0.08)]" : "border-slate-300 bg-white text-brand-600"}`}>0{i + 1}</span><div className="border-t border-slate-300 pt-4"><p className="text-[10px] font-semibold text-slate-400">{i === 0 ? "INPUT" : i === workflowSteps.length - 1 ? "OUTCOME" : "OPERATING LAYER"}</p><h3 className="mt-2 text-lg font-semibold tracking-tight text-slate-950">{i === 2 ? "Right AI employee" : title}</h3></div><p className="border-t border-slate-200 pt-4 text-sm leading-6 text-slate-600">{copy}</p></li>)}</ol></div></section>

      <section id="platform" className="section-anchor bg-[#f3f6fa] py-24 sm:py-32"><div className="mx-auto max-w-[84rem] px-5 sm:px-8 lg:px-12"><SectionIntro label="The HIRI platform" title="The operating layer for AI business work." copy="A single system for workforce configuration, structured work, governed execution, usage visibility and business outcomes." /><div className="mt-16 grid overflow-hidden border border-slate-300 bg-slate-300 lg:grid-cols-[1fr_1.18fr_1fr]"><div className="grid grid-rows-3 gap-px">{platformAreas.slice(0, 3).map(([title, copy, Icon], i) => <article key={title} className="bg-white p-7 sm:p-8"><div className="flex justify-between"><Icon className="h-5 w-5 text-brand-600" /><span className="text-[10px] text-slate-300">0{i + 1}</span></div><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></article>)}</div><div className="relative flex min-h-[32rem] flex-col items-center justify-center overflow-hidden bg-slate-950 p-10 text-center text-white"><div className="hiri-platform-orbit absolute h-80 w-80 rounded-full border border-white/10" /><div className="hiri-platform-orbit absolute h-56 w-56 rounded-full border border-blue-400/20" /><div className="relative grid h-24 w-24 place-items-center border border-blue-400/40 bg-blue-500/10"><img className="h-12 w-12" src="/hiri-logo.svg" alt="" /></div><p className="relative mt-8 text-xs font-semibold text-blue-300">HIRI operating core</p><p className="relative mt-3 max-w-xs text-sm leading-6 text-slate-400">Identity, responsibility, work, governance and outcomes share one operating context.</p></div><div className="grid grid-rows-3 gap-px">{platformAreas.slice(3).map(([title, copy, Icon], i) => <article key={title} className="bg-white p-7 sm:p-8"><div className="flex justify-between"><Icon className="h-5 w-5 text-brand-600" /><span className="text-[10px] text-slate-300">0{i + 4}</span></div><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></article>)}</div></div></div></section>

      <section className="py-24 sm:py-32"><div className="mx-auto grid max-w-[84rem] gap-16 px-5 sm:px-8 lg:grid-cols-[0.76fr_1.24fr] lg:gap-24 lg:px-12"><div><SectionIntro label="Human control" title="Governed autonomy, by design." copy="Choose how independently each employee may operate. Permissions, policies and approvals remain the boundary for sensitive action." /><div className="mt-10 flex gap-8 border-t border-slate-200 pt-5 text-xs font-semibold text-slate-500"><span>Permissions</span><span>Policies</span><span>Approvals</span></div></div><div className="relative"><div className="absolute bottom-10 left-5 top-10 w-px bg-gradient-to-b from-brand-500 to-slate-200" />{autonomyLevels.map(([num, title, copy], i) => <article key={num} className="relative grid gap-5 border-b border-slate-200 py-7 pl-16 sm:grid-cols-[0.85fr_1.15fr]"><span className={`absolute left-0 top-7 grid h-10 w-10 place-items-center rounded-full border text-[10px] font-semibold ${i === 0 ? "border-brand-500 bg-brand-500 text-white" : "border-slate-300 bg-white"}`}>{num}</span><h3 className="text-xl font-semibold">{title}</h3><p className="text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

      <section className="border-y border-slate-200 bg-slate-50 py-24 sm:py-32"><div className="mx-auto grid max-w-[84rem] gap-12 px-5 sm:px-8 lg:grid-cols-[0.72fr_1.28fr] lg:gap-20 lg:px-12"><SectionIntro label="Integrations" title="Connected to where business happens." copy="HIRI uses approved channels and business tools as controlled execution surfaces—not separate products." /><div><div className="grid border-y border-slate-300 sm:grid-cols-[12rem_1fr]"><div className="border-b border-slate-200 py-6 sm:border-b-0 sm:border-r"><Globe2 className="h-5 w-5 text-brand-600" /><p className="mt-4 text-xs font-semibold">Current / Sales-relevant</p></div><div className="grid grid-cols-2 sm:grid-cols-3">{currentIntegrations.map(x => <div key={x} className="flex items-center gap-2 px-4 py-5 text-xs font-medium text-slate-700"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />{x}</div>)}</div></div><div className="grid border-b border-slate-300 sm:grid-cols-[12rem_1fr]"><div className="border-b border-slate-200 py-6 sm:border-b-0 sm:border-r"><PlugZap className="h-5 w-5 text-slate-500" /><p className="mt-4 text-xs font-semibold">Designed to connect with</p></div><div className="grid grid-cols-2 sm:grid-cols-3">{integrationDirection.map(([x, Icon]) => <div key={x} className="flex items-center gap-2 px-4 py-5 text-xs font-medium text-slate-600"><Icon className="h-3.5 w-3.5 text-slate-400" />{x}</div>)}</div></div></div></div></section>

      <section className="py-24 sm:py-32"><div className="mx-auto grid max-w-[84rem] gap-12 px-5 sm:px-8 lg:grid-cols-[0.65fr_1.35fr] lg:gap-20 lg:px-12"><SectionIntro label="Business impact" title="AI work with operating discipline." copy="Move faster while preserving the visibility and control a real business needs." /><div className="grid border-t border-slate-300 sm:grid-cols-2">{benefits.map(([title, copy, Icon], i) => <article key={title} className={`border-b border-slate-200 py-7 sm:p-7 ${i % 2 === 0 ? "sm:border-r" : ""}`}><div className="flex gap-5"><Icon className="mt-1 h-5 w-5 shrink-0 text-brand-600" /><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div></div></article>)}</div></div></section>

      <section className="bg-[#eef3f9] py-24 sm:py-32"><div className="mx-auto max-w-[84rem] px-5 sm:px-8 lg:px-12"><div className="mb-14 flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionIntro label="Operations center" title="See the workforce. See the work. Stay in control." copy="Assignments, progress, approvals, activity and AI cost—understood in one operating context." /><p className="text-xs text-slate-500">Illustrative product preview</p></div><ProductSurface /></div></section>

      <section id="about" className="section-anchor py-24 sm:py-32"><div className="mx-auto max-w-[84rem] px-5 sm:px-8 lg:px-12"><div className="grid overflow-hidden border border-slate-200 lg:grid-cols-[1.1fr_0.9fr]"><div className="p-8 sm:p-12 lg:p-16"><SectionIntro label="About HIRI" title="Operate AI workers like a real workforce." copy="HIRI gives businesses a structured way to operate AI workers with responsibilities, tools, controls and measurable work." /></div><div className="relative bg-slate-950 p-8 text-white sm:p-12 lg:p-16"><div className="hiri-mark-geometry absolute -bottom-40 -right-40 h-96 w-96 opacity-20" /><div className="relative space-y-8">{["Start with one employee.", "Build a specialized team.", "Expand into departments when ready."].map((x, i) => <div key={x} className="grid grid-cols-[2rem_1fr] gap-5 border-b border-white/10 pb-8 last:border-0"><span className="text-xs font-semibold text-blue-400">0{i + 1}</span><p className="text-lg font-semibold">{x}</p></div>)}</div></div></div></div></section>

      <section id="demo" className="section-anchor bg-brand-600 text-white"><div className="relative mx-auto max-w-[90rem] overflow-hidden px-5 py-20 sm:px-8 sm:py-24 lg:px-12"><div className="hiri-cta-mark absolute -right-20 -top-40 h-[34rem] w-[34rem] opacity-25" /><div className="relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-sm font-semibold text-blue-100">Build your AI workforce</p><h2 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1.05] tracking-[-0.04em] sm:text-6xl">Keep humans in control as you scale.</h2><p className="mt-6 text-lg text-blue-100">Start with Sales. Expand into teams and departments when your business is ready.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="#demo" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-md bg-white px-5 py-3 text-sm font-semibold text-brand-700">Book a demo<ArrowRight className="h-4 w-4" /></a><Link to="/login" className="inline-flex min-h-12 items-center justify-center rounded-md border border-white/25 px-5 py-3 text-sm font-semibold">Log in</Link></div></div></div></section>
    </main>
    <footer className="bg-[#050b14] text-slate-400"><div className="mx-auto max-w-[90rem] px-5 py-16 sm:px-8 lg:px-12"><div className="grid gap-14 lg:grid-cols-[1.5fr_0.7fr_0.7fr]"><div><Brand inverted /><p className="mt-7 max-w-sm text-2xl font-semibold tracking-tight text-white">The operating system for your AI workforce.</p><p className="mt-4 max-w-sm text-sm leading-6 text-slate-500">AI employees and departments performing real business work with human control.</p></div><div><p className="text-xs font-semibold text-white">Product</p><div className="mt-5 grid gap-3">{[["Platform", "#platform"], ["Sales", "#sales"], ["AI Workforce", "#product"], ["How it works", "#how-it-works"]].map(([x, href]) => <a key={x} href={href} className="text-sm hover:text-white">{x}</a>)}</div></div><div><p className="text-xs font-semibold text-white">Company</p><div className="mt-5 grid gap-3"><a href="#about" className="text-sm hover:text-white">About</a><a href="#demo" className="text-sm hover:text-white">Contact</a><Link to="/login" className="text-sm hover:text-white">Log in</Link></div></div></div><div className="mt-16 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs text-slate-600 sm:flex-row sm:justify-between"><p>© 2026 HIRI</p><p>AI workforce. Human control.</p></div></div></footer>
  </div>;
}
